# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The OCX Authors
"""The acceptance suite as Bazel test targets — one `sh_test` per module (C-024).

`acceptance_suite()` is the whole surface: it writes one runner script and
declares one `sh_test` per `test/tests/test_*.py`, each of them tagged
`external`, `exclusive` and `local`.

**`sh_test` is not a native rule on a Bazel 9 pin.** It is loaded from
`@rules_shell//shell:sh_test.bzl` below; without that load the package fails at
load time with `name 'sh_test' is not defined`, and no amount of `bazel_dep` on
`rules_shell` changes that (BZL-LARK-10).

## The three tags, and why each of them is the one it is

**`external` — measured, not intuited.** WP-35's `--prove-s015` ran four
`sh_test` targets over one script on this exact pin (bazel 9.2.0,
`rules_shell` 0.8.0, `--disk_cache` only), cold / warm-same-server /
warm-fresh-server:

    target            tags                             cold   warm    warm
                                                              (same)  (fresh)
    sibling           -                                 ran   CACHED  CACHED
    acc_local_only    local, exclusive                  ran   CACHED  ran
    acc_nocache       local, exclusive, no-cache        ran   CACHED  ran
    acc_external      local, external, exclusive        ran   ran     ran

So `external` is the only tag that stops a test result being reused. `no-cache`
— the spelling a reader reaches for first — leaves the local action-cache hit
in place, so a developer running `bazel test //test:all` twice in a row gets
`(cached)` back from a `no-cache`-tagged acceptance target. `local` is not it
either: it suppresses the *disk*-cache hit (Bazel treats `--disk_cache` as a
remote cache and `local` implies `no-remote`) while leaving the action-cache
hit — which is exactly the developer-machine case. Nothing in the action graph
tracks the docker-compose stack these tests talk to, so a cached pass is a pass
against a world that may have changed, and that is Block-tier.

**`exclusive` — serialisation, and it belongs on the target.** One compose
stack on one set of ports, so two acceptance targets running at once share it.
The same probe measured three `exclusive`-tagged 0.7 s tests running with
disjoint windows (0 overlapping pairs) while three untagged ones overlapped
pairwise, with no `--local_test_jobs` anywhere. A global `--local_test_jobs=1`
would buy the same serialisation and would also serialise the 34 Rust test
targets, which is stage 2's entire win — an rc line is per-command and never
per-target-pattern, so there is no way to scope it to this package.

**`local`** keeps the suite out of the sandbox: it drives `docker compose`, a
uv-managed virtualenv and a cargo-built binary, none of which survive a
sandboxed working directory. It is carried in addition to `external`, never
instead of it.

## What this suite does NOT declare, and why that is deliberate

BZL-TEST-12 asks a test to write only under `$TEST_TMPDIR` and to resolve its
inputs through runfiles. This suite cannot: its subject is a compose stack, a
`test/bin/ocx` built by `cargo`, and a `.venv` uv materialises — three inputs
that are not action inputs and cannot be made into them. Rather than pretend
otherwise with a `glob(["**"])` that would build 172 symlink forests over the
same ~4500 files and still not cover the stack, each target declares only its
own module plus the anchor, and the runner asserts the rest loudly at runtime.
The honest consequence is written into the tags: `external` says the result is
never reused, so an undeclared input can never produce a stale green.
"""

load("@rules_shell//shell:sh_test.bzl", "sh_test")

visibility("private")

# C-024's tag set. Sorted, because `bazel query` reports tags sorted and
# `task test:bazel:tags` reduces that output into the table the S-015
# comparator judges — two readers of one fact, and they have to line up.
ACCEPTANCE_TAGS = [
    "exclusive",
    "external",
    "local",
]

# The environment the suite reads that Bazel does not synthesise. `HOME` is
# uv's cache root and ocx's default store root; `DOCKER_HOST` /
# `XDG_RUNTIME_DIR` are how a rootless docker daemon is found; the two port
# knobs are the ones `docker-compose.yml`, `test/conftest.py` and
# `test/taskfile.yml` all read, so a machine that moved the registry off 5000
# moves this suite with it. Inheriting is safe here for the same reason the
# tags say: nothing this target produces is ever reused.
_INHERITED_ENV = [
    "DOCKER_CONFIG",
    "DOCKER_HOST",
    "HOME",
    "OCX_TEST_MIRROR_PORT",
    "OCX_TEST_REGISTRY_PORT",
    "SSH_AUTH_SOCK",
    "USER",
    "XDG_RUNTIME_DIR",
]

_RUNNER = """#!/bin/sh
# GENERATED by test/bazel.bzl. There is no source copy of this file: it is
# written by `ctx.actions.write`, so its bytes are an action input and a change
# to them re-keys every target that runs it.
#
# argv: <uv rlocationpath> <package-relative module> [extra pytest arg ...]
set -eu

fail() {
    echo "acceptance sh_test: $*" >&2
    exit 1
}

[ "$#" -ge 2 ] || fail "usage: <uv rlocationpath> <module> [pytest arg ...]"
uv_rlocation="$1"
module="$2"
shift 2

# Every one of these is set by `bazel test` and by nothing else. A missing one
# means this script was invoked some other way, and the checks below would then
# be measuring a directory layout that is not the one under test.
[ -n "${TEST_SRCDIR:-}" ] || fail "TEST_SRCDIR is unset - run this through \\`bazel test\\`"
[ -n "${TEST_WORKSPACE:-}" ] || fail "TEST_WORKSPACE is unset - run this through \\`bazel test\\`"
[ -n "${TEST_TMPDIR:-}" ] || fail "TEST_TMPDIR is unset - run this through \\`bazel test\\`"

uv="$TEST_SRCDIR/$uv_rlocation"
[ -x "$uv" ] || fail "no executable uv launcher at $uv (@tools//:uv)"

# The suite runs in the SOURCE tree, and the path to it is resolved from a
# runfile rather than written into the BUILD file: an absolute path in a
# declared output or a rule attribute is BZL-HERM-01, and it would also make
# this package unusable from any other checkout. `conftest.py` is a runfile of
# every acceptance target; under `local` (no sandbox) Bazel materialises it as
# a symlink into the source tree, so resolving that symlink is the anchor.
anchor="$TEST_SRCDIR/$TEST_WORKSPACE/test/conftest.py"
[ -e "$anchor" ] || fail "no runfile at $anchor - the anchor is not in this target's data"
real_anchor=$(readlink -f "$anchor") || fail "cannot resolve the anchor runfile $anchor"
suite=$(dirname "$real_anchor")

# A runfiles tree materialised as COPIES rather than symlinks resolves to
# itself, and every check below would then pass against a tree that is not the
# source tree - the shape where a green says nothing. Refused by name.
case "$suite" in
    *.runfiles/* | */bazel-out/*)
        fail "runfiles are copies here, so $suite is not the source tree"
        ;;
esac

[ -f "$suite/pyproject.toml" ] || fail "$suite carries no pyproject.toml - wrong tree"
[ -f "$suite/$module" ] || fail "no acceptance module at $suite/$module"

# Built by `cargo` through `task test`, never by Bazel: there is no
# `rust_binary` for `ocx` in this graph (the crates carry `rust_library` and
# `rust_test` only). A suite run against a stale or absent binary is silent,
# so its absence is a refusal rather than a skip.
ocx="$suite/bin/ocx"
[ -x "$ocx" ] || fail "no acceptance binary at $ocx - \\`task test\\` builds and copies it"

OCX_COMMAND="$ocx"
OCX_SHIM_BINARY="$suite/bin/ocx-shim"
OCX_INSECURE_REGISTRIES="localhost:${OCX_TEST_REGISTRY_PORT:-5000}"
export OCX_COMMAND OCX_SHIM_BINARY OCX_INSECURE_REGISTRIES

# pytest arenas, and why they are NOT under $TEST_TMPDIR (BZL-TEST-12's usual
# answer). Measured on 9.2.0: bazel symlinks the workspace's `.git` into
# `execroot/_main`, and $TEST_TMPDIR lives under it — so `git rev-parse` from a
# pytest `tmp_path` answers the execroot as its toplevel and every test that
# shells out to git inside its own arena is silently inside a repository.
# `test_git_http_fixture.py::test_shim_preserves_exit_code_and_stderr_bytes`
# caught it: its positive control (`git rev-parse HEAD` in an empty directory
# must fail) returned this checkout's HEAD and exit 0.
#
# So the arenas go where `test/taskfile.yml` already puts them — disk-backed,
# off the reaped /tmp, outside every git tree — with a `-bazel` suffix so the
# two entry points never delete each other's basetemp at startup.
[ -n "${HOME:-}" ] || fail "HOME is unset - the arena root and uv's cache both need it"
checkout=$(basename "$(dirname "$suite")")
basetemp="$HOME/.cache/ocx-pytest/$checkout-bazel"
TMPDIR="$HOME/.cache/ocx-test-tmp"
mkdir -p "$basetemp" "$TMPDIR"
export TMPDIR

set -- --basetemp="$basetemp" "$module" "$@"
[ -z "${XML_OUTPUT_FILE:-}" ] || set -- "--junit-xml=$XML_OUTPUT_FILE" "$@"

cd "$suite"

# One acceptance run at a time on this HOST. `exclusive` serialises the targets
# of one bazel invocation; it says nothing about a `task test:parallel` running
# in a sibling worktree, and both drive the same compose stack on the same
# ports. `test/taskfile.yml` computes this same path for its own pytest step,
# so the two entry points contend on one file rather than on two.
#
# Not under the repository. A `<checkout>/.agents/…` path resolves to a
# DIFFERENT file in each of the four fixed worktrees and in every agent
# worktree, so it would serialise nothing across exactly the checkouts that
# share the registry — the contention it exists to prevent. The key is the
# registry port, because the port is what identifies the contended stack: a
# second project on another port is not a competitor and must not queue.
lock_dir="$HOME/.cache/ocx"
mkdir -p "$lock_dir"
lock="$lock_dir/acceptance-suite-${OCX_TEST_REGISTRY_PORT:-5000}.lock"

if command -v flock >/dev/null 2>&1; then
    exec flock "$lock" "$uv" run pytest "$@"
fi

# Never silently: a host with no flock(1) (macOS ships none) runs unserialised,
# and whoever reads the log has to be able to see that it did.
echo "acceptance sh_test: no flock(1) on this host - running unserialised, $lock untaken" >&2
exec "$uv" run pytest "$@"
"""

def _acceptance_runner_impl(ctx):
    runner = ctx.actions.declare_file(ctx.label.name + ".sh")
    ctx.actions.write(output = runner, content = _RUNNER, is_executable = True)
    return DefaultInfo(files = depset([runner]))

_acceptance_runner = rule(
    implementation = _acceptance_runner_impl,
    doc = """Materialise the shared runner.

`ctx.actions.write` rather than a `genrule` heredoc: the script's text reaches
the file byte for byte with no shell quoting layer between, so a `$`, a
backtick or a newline in `_RUNNER` cannot change meaning on the way out.
""",
)

def _target_name(module):
    """`tests/test_install.py` -> `test_install`, matching `//test:test_install`.

    The spelling is a contract, not a convenience: `bazel_accept_proofs.py`'s
    `module_target()` maps a module to that label, and `SCOPED_ROWS` is read as
    the crate -> target selection query through it. A rename here unwires S-004
    without reddening anything in this package.
    """
    if not module.startswith("tests/") or not module.endswith(".py"):
        fail("acceptance module %r is not a `tests/*.py` path" % module)
    return module[len("tests/"):-len(".py")]

def acceptance_suite(name, modules, uv = "@tools//:uv", extra_pytest_args = None):
    """One `sh_test` per acceptance module, plus the runner they share.

    Args:
      name: the runner target's name; the tests are named after their modules.
      modules: package-relative `tests/test_*.py` paths. Empty is refused - a
        glob that matched nothing would otherwise declare zero targets and
        `bazel build //test:all` would exit 0 over an empty package, which is
        the exact shape a count floor exists to catch.
      uv: the label of the `uv` launcher; `@tools//:uv` resolves from
        `ocx.lock`, never from `PATH`.
      extra_pytest_args: appended after the module path on every target.
    """
    if not modules:
        fail("acceptance_suite: no modules - `glob([\"tests/test_*.py\"])` matched nothing")

    _acceptance_runner(name = name)

    for module in modules:
        sh_test(
            name = _target_name(module),
            size = "medium",
            timeout = "long",
            srcs = [name],
            args = ["$(rlocationpath %s)" % uv, module] + (extra_pytest_args or []),
            data = [
                module,
                uv,
                ":suite_anchor",
            ],
            env_inherit = _INHERITED_ENV,
            tags = ACCEPTANCE_TAGS,
        )
