# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  coverage: ./taskfiles/coverage.taskfile.yml
  recordings: ./taskfiles/recordings.taskfile.yml
  test:
    taskfile: ./test/taskfile.yml
    dir: ./test
  website:
    taskfile: ./website/taskfile.yml
    dir: ./website

tasks:
  push:
    vars:
      DATE:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
    cmds:
      - git add .
      - git commit -m "{{ .DATE }}"
      - git push {{ .CLI_ARGS }}

  checkpoint:
    cmds:
      - if: '! [[ $(git show -s --format=%s HEAD) == "Checkpoint" ]]'
        cmd: git commit --allow-empty -m "Checkpoint"
      - cmd: git add .
      - cmd: git commit --amend --no-edit --allow-empty

  default:
    cmd: cargo check
