// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OCX Authors

use std::process::ExitCode;

use clap::Parser;
use ocx_lib::{cli, env};

use crate::app::CommandError;

/// Writes a `.envrc` file in the current directory that wires
/// `ocx shell direnv` into [direnv](https://direnv.net). Run `direnv allow`
/// afterwards to activate.
///
/// The generated `.envrc` watches `ocx.toml` and `ocx.lock` so direnv
/// re-runs the hook when either changes; the hook itself is
/// `eval "$(ocx shell direnv)"`. `ocx shell direnv` always emits bash —
/// direnv sources `.envrc` in a bash sub-shell regardless of the user's
/// interactive shell — so the generated file is portable across teams
/// using different interactive shells.
#[derive(Parser)]
pub struct GenerateDirenv {
    /// Overwrite an existing `.envrc` in the current directory.
    #[clap(long)]
    force: bool,
}

const ENVRC_CONTENT: &str = "# Generated by ocx — run 'direnv allow' to activate\n\
                             # Requires: direnv (https://direnv.net)\n\
                             watch_file ocx.toml ocx.lock\n\
                             eval \"$(ocx shell direnv)\"\n";

impl GenerateDirenv {
    pub async fn execute(&self, context: crate::app::Context) -> anyhow::Result<ExitCode> {
        let cwd = env::current_dir()?;
        let envrc = cwd.join(".envrc");
        if envrc.exists() && !self.force {
            return Err(CommandError::new(
                format!(
                    ".envrc already exists at {}; pass --force to overwrite",
                    envrc.display()
                ),
                cli::ExitCode::ConfigError,
            )
            .into());
        }
        tokio::fs::write(&envrc, ENVRC_CONTENT).await?;
        context
            .ui()
            .success(format!("Wrote {}; run `direnv allow` to activate.", envrc.display()));
        Ok(ExitCode::SUCCESS)
    }
}
