# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The OCX Authors
"""Acceptance tests for ``ocx direnv init`` and ``ocx direnv export``.

- ``ocx direnv init`` -> creates ``.envrc`` with the spec content
- bare ``ocx direnv`` -> defaults to ``init`` (same behavior)
- ``ocx direnv init`` when ``.envrc`` exists -> exit 78 (ConfigError),
  preserve user content
- ``ocx direnv init --force`` when ``.envrc`` exists -> overwrites
- ``ocx direnv export`` (default) -> installs a locked-but-unpulled tool on
  miss, then emits its env
- ``ocx direnv export --no-pull`` -> stays strictly offline: warns + omits a
  missing tool, never mutates the store

We bypass ``OcxRunner.run`` because the command writes to / reads from CWD, and
the runner does not expose a ``cwd=`` parameter (same pattern as
``test_lock.py`` / ``test_project_pull.py``).
"""
from __future__ import annotations

import subprocess
from pathlib import Path
from uuid import uuid4

from src.helpers import make_package
from src.runner import OcxRunner, PackageInfo


# Exit code constant - matches crates/ocx_lib/src/cli/exit_code.rs::ExitCode::ConfigError
EXIT_CONFIG = 78


# Spec content from plan_project_toolchain.md lines 813-818.
# Constructed by concatenation rather than a single triple-quoted literal so
# the trailing-newline contract on each line is unambiguous.
EXPECTED_ENVRC = (
    "# Generated by ocx — run 'direnv allow' to activate\n"
    "# Requires: direnv (https://direnv.net)\n"
    "watch_file ocx.toml ocx.lock\n"
    'eval "$(ocx direnv export)"\n'
)


def _run_direnv_init(
    ocx: OcxRunner,
    cwd: Path,
    *extra: str,
) -> subprocess.CompletedProcess[str]:
    """Run ``ocx direnv init`` from ``cwd``.

    Bypasses ``OcxRunner.run`` to set the working directory: the command
    writes ``.envrc`` to CWD, so test isolation requires CWD = tmp_path.
    """
    cmd = [str(ocx.binary), "direnv", "init", *extra]
    return subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        env=ocx.env,
    )


def test_direnv_init_creates_envrc(ocx: OcxRunner, tmp_path: Path) -> None:
    """Fresh project dir -> .envrc written with the spec content; exit 0."""
    result = _run_direnv_init(ocx, tmp_path)
    assert result.returncode == 0, (
        f"expected exit 0; got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    envrc = tmp_path / ".envrc"
    assert envrc.exists(), "expected .envrc to be created"
    assert envrc.read_text() == EXPECTED_ENVRC


def test_direnv_init_refuses_when_envrc_exists(
    ocx: OcxRunner, tmp_path: Path
) -> None:
    """Existing .envrc -> exit 78 (ConfigError); existing file untouched."""
    envrc = tmp_path / ".envrc"
    envrc.write_text("user content\n")
    result = _run_direnv_init(ocx, tmp_path)
    assert result.returncode == EXIT_CONFIG, (
        f"expected ConfigError ({EXIT_CONFIG}) when .envrc exists; "
        f"got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert envrc.read_text() == "user content\n", (
        "user content must be preserved without --force"
    )


def test_direnv_init_force_overwrites(
    ocx: OcxRunner, tmp_path: Path
) -> None:
    """Existing .envrc + --force -> overwritten with spec content; exit 0."""
    envrc = tmp_path / ".envrc"
    envrc.write_text("user content\n")
    result = _run_direnv_init(ocx, tmp_path, "--force")
    assert result.returncode == 0, (
        f"expected exit 0 with --force; got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert envrc.read_text() == EXPECTED_ENVRC


def test_bare_direnv_defaults_to_init(ocx: OcxRunner, tmp_path: Path) -> None:
    """Bare ``ocx direnv`` (no subcommand) behaves like ``ocx direnv init``."""
    result = subprocess.run(
        [str(ocx.binary), "direnv"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        env=ocx.env,
    )
    assert result.returncode == 0, (
        f"expected exit 0; got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    envrc = tmp_path / ".envrc"
    assert envrc.exists(), "bare `ocx direnv` must write .envrc"
    assert envrc.read_text() == EXPECTED_ENVRC


# ---------------------------------------------------------------------------
# ocx direnv export — eager default (install on miss), --no-pull stays offline
# ---------------------------------------------------------------------------


def _make_locked_unpulled_project(ocx: OcxRunner, tmp_path: Path, label: str) -> Path:
    """Publish a package and create a locked-but-NOT-pulled project dir."""
    short = uuid4().hex[:8]
    repo = f"t_{short}_{label}"
    make_package(ocx, repo, "1.0.0", tmp_path, new=True, cascade=False, bins=["tool"])
    fq = f"{ocx.registry}/{repo}:1.0.0"

    project = tmp_path / f"proj_{label}"
    project.mkdir()
    (project / "ocx.toml").write_text(f'[tools]\ntool = "{fq}"\n')

    lock = subprocess.run(
        [str(ocx.binary), "lock", "--no-pull"],
        cwd=project,
        capture_output=True,
        text=True,
        env=ocx.env,
    )
    assert lock.returncode == 0, f"lock --no-pull failed: {lock.stderr}"
    return project


def _run_export(ocx: OcxRunner, cwd: Path, *extra: str) -> subprocess.CompletedProcess[str]:
    """Run ``ocx direnv export`` from ``cwd`` (reads the nearest ocx.toml)."""
    return subprocess.run(
        [str(ocx.binary), "direnv", "export", *extra],
        cwd=cwd,
        capture_output=True,
        text=True,
        env=ocx.env,
    )


def _tool_exports(stdout: str) -> list[str]:
    """Export lines for resolved tools."""
    return [line for line in stdout.splitlines() if line.startswith("export ")]


def test_direnv_export_default_installs_missing(ocx: OcxRunner, tmp_path: Path) -> None:
    """Default ``ocx direnv export`` materialises a locked-but-unpulled tool on
    miss, then emits its bash env (mirrors ``ocx env``'s eager default)."""
    project = _make_locked_unpulled_project(ocx, tmp_path, "export_eager")

    result = _run_export(ocx, project)
    assert result.returncode == 0, f"expected exit 0; stderr:\n{result.stderr}"
    assert _tool_exports(result.stdout), (
        f"default export must install the missing tool and emit its env\nstdout:\n{result.stdout}"
    )
    assert "not installed" not in result.stderr, result.stderr


def test_direnv_export_no_pull_stays_offline(ocx: OcxRunner, tmp_path: Path) -> None:
    """``ocx direnv export --no-pull`` never contacts the registry: a
    locked-but-unmaterialised tool is warned about, omitted, and NOT installed —
    a second run still reports it missing (store untouched). Exit stays 0 so the
    prompt is never broken."""
    project = _make_locked_unpulled_project(ocx, tmp_path, "export_nopull")

    result = _run_export(ocx, project, "--no-pull")
    assert result.returncode == 0, f"expected exit 0; stderr:\n{result.stderr}"
    assert "not installed" in result.stderr, (
        f"missing-tool note expected on stderr\nstderr:\n{result.stderr}"
    )
    assert not _tool_exports(result.stdout), (
        f"unmaterialised tool must be omitted\nstdout:\n{result.stdout}"
    )

    again = _run_export(ocx, project, "--no-pull")
    assert again.returncode == 0, again.stderr
    assert "not installed" in again.stderr, (
        f"--no-pull must never materialise the tool\nstderr:\n{again.stderr}"
    )


# ---------------------------------------------------------------------------
# OCX_INDEX negative path — a broken index home (a regular file, not a
# directory) must never crash `ocx direnv export` or toolchain resolution.
# Every scenario below is a documented finding of *actual* behaviour, probed
# directly against the binary before writing the assertions (see PR review
# W6 follow-up): there is no dedicated ADR clause pinning these exit codes,
# so each assertion is a regression guard on the current, non-panicking
# contract rather than a restatement of a written spec.
# ---------------------------------------------------------------------------


def _set_broken_index(ocx: OcxRunner, path: Path) -> None:
    """Point OCX_INDEX at a regular file so any index read/write under it
    hits ENOTDIR — the simplest reproducible "invalid index location"."""
    path.write_text("not a directory")
    ocx.env["OCX_INDEX"] = str(path)


def test_direnv_export_default_survives_broken_ocx_index(
    ocx: OcxRunner, tmp_path: Path
) -> None:
    """A locked-but-unpulled tool still installs when OCX_INDEX is broken.

    The default eager-pull path (`test_direnv_export_default_installs_missing`)
    tries the local index first; a broken index home fails that read/write,
    but the resolver falls back to a live registry fetch instead of
    aborting. The failure is surfaced as a stderr warning — never silent,
    never a panic (`quality-rust-exit_codes.md`: no numeric exit code changes
    when a lower layer self-heals via fallback, so exit stays 0)."""
    project = _make_locked_unpulled_project(ocx, tmp_path, "export_bad_index")

    _set_broken_index(ocx, tmp_path / "bad_ocx_index")
    try:
        result = _run_export(ocx, project)
    finally:
        del ocx.env["OCX_INDEX"]

    assert result.returncode == 0, (
        f"expected exit 0 (network fallback survives a broken index); stderr:\n{result.stderr}"
    )
    assert result.returncode != 101, f"must not panic; stderr:\n{result.stderr}"
    assert "panicked" not in result.stderr.lower(), result.stderr
    assert _tool_exports(result.stdout), (
        f"a broken OCX_INDEX must still resolve via network fallback\nstdout:\n{result.stdout}"
    )
    assert "index" in result.stderr.lower(), (
        f"the broken index location must be surfaced on stderr, not swallowed silently\nstderr:\n{result.stderr}"
    )


def test_direnv_export_broken_ocx_index_is_a_noop_once_installed(
    ocx: OcxRunner, tmp_path: Path
) -> None:
    """A broken OCX_INDEX has zero effect once the tool is already installed.

    Project-tier env composition for an already-pulled lock reads the
    pinned platform-manifest digest straight from the machine-global
    blob/package store; it never consults the index
    (`adr_index_indirection.md` Decision D — locks are index-free). A
    redirected-but-broken index home must not even be touched, let alone
    break the export."""
    short = uuid4().hex[:8]
    repo = f"t_{short}_export_noop"
    make_package(ocx, repo, "1.0.0", tmp_path, new=True, cascade=False, bins=["tool"])
    fq = f"{ocx.registry}/{repo}:1.0.0"

    project = tmp_path / "proj_noop"
    project.mkdir()
    (project / "ocx.toml").write_text(f'[tools]\ntool = "{fq}"\n')

    lock = subprocess.run(
        [str(ocx.binary), "lock"],  # normal lock + pull: tool is installed before the probe
        cwd=project,
        capture_output=True,
        text=True,
        env=ocx.env,
    )
    assert lock.returncode == 0, f"lock failed: {lock.stderr}"

    _set_broken_index(ocx, tmp_path / "bad_ocx_index_noop")
    try:
        result = _run_export(ocx, project)
    finally:
        del ocx.env["OCX_INDEX"]

    assert result.returncode == 0, f"expected exit 0; stderr:\n{result.stderr}"
    assert "panicked" not in result.stderr.lower(), result.stderr
    assert _tool_exports(result.stdout), (
        f"an already-installed tool must still resolve\nstdout:\n{result.stdout}"
    )


def test_toolchain_add_fails_cleanly_not_panic_on_broken_ocx_index(
    ocx: OcxRunner, published_package: PackageInfo, tmp_path: Path
) -> None:
    """Toolchain resolution (`ocx add`) fails cleanly, never panics, when
    OCX_INDEX names a broken location.

    `ocx add` resolves a fresh binding: the local index write fails, the
    resolver falls back to the OCI chain, and that fallback also cannot
    write its dispatch object into the broken location. The whole chain
    must surface as a clean nonzero exit with a diagnosable stderr message
    — not a crash and not a silently-empty `ocx.toml`."""
    pkg = published_package
    project = tmp_path / "proj_add_bad_index"
    project.mkdir()
    (project / "ocx.toml").write_text("[tools]\n")

    _set_broken_index(ocx, tmp_path / "bad_ocx_index_add")
    try:
        result = subprocess.run(
            [str(ocx.binary), "add", pkg.short],
            cwd=project,
            capture_output=True,
            text=True,
            env=ocx.env,
        )
    finally:
        del ocx.env["OCX_INDEX"]

    assert result.returncode != 0, (
        f"a broken OCX_INDEX must fail the resolve, not silently succeed\nstdout:\n{result.stdout}"
    )
    assert result.returncode != 101, f"must not panic; stderr:\n{result.stderr}"
    assert "panicked" not in result.stderr.lower(), result.stderr
    assert result.stderr.strip(), "a clean failure must leave a diagnosable message on stderr"
