# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The OCX Authors
"""Acceptance tests for ``ocx direnv init`` and ``ocx direnv export``.

- ``ocx direnv init`` -> creates ``.envrc`` with the spec content
- bare ``ocx direnv`` -> defaults to ``init`` (same behavior)
- ``ocx direnv init`` when ``.envrc`` exists -> exit 78 (ConfigError),
  preserve user content
- ``ocx direnv init --force`` when ``.envrc`` exists -> overwrites
- ``ocx direnv export`` (default) -> installs a locked-but-unpulled tool on
  miss, then emits its env
- ``ocx direnv export --no-pull`` -> stays strictly offline: warns + omits a
  missing tool, never mutates the store

We bypass ``OcxRunner.run`` because the command writes to / reads from CWD, and
the runner does not expose a ``cwd=`` parameter (same pattern as
``test_lock.py`` / ``test_project_pull.py``).
"""
from __future__ import annotations

import subprocess
from pathlib import Path
from uuid import uuid4

from src.helpers import make_package
from src.runner import OcxRunner


# Exit code constant - matches crates/ocx_lib/src/cli/exit_code.rs::ExitCode::ConfigError
EXIT_CONFIG = 78


# Spec content from plan_project_toolchain.md lines 813-818.
# Constructed by concatenation rather than a single triple-quoted literal so
# the trailing-newline contract on each line is unambiguous.
EXPECTED_ENVRC = (
    "# Generated by ocx — run 'direnv allow' to activate\n"
    "# Requires: direnv (https://direnv.net)\n"
    "watch_file ocx.toml ocx.lock\n"
    'eval "$(ocx direnv export)"\n'
)


def _run_direnv_init(
    ocx: OcxRunner,
    cwd: Path,
    *extra: str,
) -> subprocess.CompletedProcess[str]:
    """Run ``ocx direnv init`` from ``cwd``.

    Bypasses ``OcxRunner.run`` to set the working directory: the command
    writes ``.envrc`` to CWD, so test isolation requires CWD = tmp_path.
    """
    cmd = [str(ocx.binary), "direnv", "init", *extra]
    return subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        env=ocx.env,
    )


def test_direnv_init_creates_envrc(ocx: OcxRunner, tmp_path: Path) -> None:
    """Fresh project dir -> .envrc written with the spec content; exit 0."""
    result = _run_direnv_init(ocx, tmp_path)
    assert result.returncode == 0, (
        f"expected exit 0; got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    envrc = tmp_path / ".envrc"
    assert envrc.exists(), "expected .envrc to be created"
    assert envrc.read_text() == EXPECTED_ENVRC


def test_direnv_init_refuses_when_envrc_exists(
    ocx: OcxRunner, tmp_path: Path
) -> None:
    """Existing .envrc -> exit 78 (ConfigError); existing file untouched."""
    envrc = tmp_path / ".envrc"
    envrc.write_text("user content\n")
    result = _run_direnv_init(ocx, tmp_path)
    assert result.returncode == EXIT_CONFIG, (
        f"expected ConfigError ({EXIT_CONFIG}) when .envrc exists; "
        f"got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert envrc.read_text() == "user content\n", (
        "user content must be preserved without --force"
    )


def test_direnv_init_force_overwrites(
    ocx: OcxRunner, tmp_path: Path
) -> None:
    """Existing .envrc + --force -> overwritten with spec content; exit 0."""
    envrc = tmp_path / ".envrc"
    envrc.write_text("user content\n")
    result = _run_direnv_init(ocx, tmp_path, "--force")
    assert result.returncode == 0, (
        f"expected exit 0 with --force; got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert envrc.read_text() == EXPECTED_ENVRC


def test_bare_direnv_defaults_to_init(ocx: OcxRunner, tmp_path: Path) -> None:
    """Bare ``ocx direnv`` (no subcommand) behaves like ``ocx direnv init``."""
    result = subprocess.run(
        [str(ocx.binary), "direnv"],
        cwd=tmp_path,
        capture_output=True,
        text=True,
        env=ocx.env,
    )
    assert result.returncode == 0, (
        f"expected exit 0; got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    envrc = tmp_path / ".envrc"
    assert envrc.exists(), "bare `ocx direnv` must write .envrc"
    assert envrc.read_text() == EXPECTED_ENVRC


# ---------------------------------------------------------------------------
# ocx direnv export — eager default (install on miss), --no-pull stays offline
# ---------------------------------------------------------------------------


def _make_locked_unpulled_project(ocx: OcxRunner, tmp_path: Path, label: str) -> Path:
    """Publish a package and create a locked-but-NOT-pulled project dir."""
    short = uuid4().hex[:8]
    repo = f"t_{short}_{label}"
    make_package(ocx, repo, "1.0.0", tmp_path, new=True, cascade=False, bins=["tool"])
    fq = f"{ocx.registry}/{repo}:1.0.0"

    project = tmp_path / f"proj_{label}"
    project.mkdir()
    (project / "ocx.toml").write_text(f'[tools]\ntool = "{fq}"\n')

    lock = subprocess.run(
        [str(ocx.binary), "lock", "--no-pull"],
        cwd=project,
        capture_output=True,
        text=True,
        env=ocx.env,
    )
    assert lock.returncode == 0, f"lock --no-pull failed: {lock.stderr}"
    return project


def _run_export(ocx: OcxRunner, cwd: Path, *extra: str) -> subprocess.CompletedProcess[str]:
    """Run ``ocx direnv export`` from ``cwd`` (reads the nearest ocx.toml)."""
    return subprocess.run(
        [str(ocx.binary), "direnv", "export", *extra],
        cwd=cwd,
        capture_output=True,
        text=True,
        env=ocx.env,
    )


def test_direnv_export_default_installs_missing(ocx: OcxRunner, tmp_path: Path) -> None:
    """Default ``ocx direnv export`` materialises a locked-but-unpulled tool on
    miss, then emits its bash env (mirrors ``ocx env``'s eager default)."""
    project = _make_locked_unpulled_project(ocx, tmp_path, "export_eager")

    result = _run_export(ocx, project)
    assert result.returncode == 0, f"expected exit 0; stderr:\n{result.stderr}"
    assert "export" in result.stdout, (
        f"default export must install the missing tool and emit its env\nstdout:\n{result.stdout}"
    )
    assert "not installed" not in result.stderr, result.stderr


def test_direnv_export_no_pull_stays_offline(ocx: OcxRunner, tmp_path: Path) -> None:
    """``ocx direnv export --no-pull`` never contacts the registry: a
    locked-but-unmaterialised tool is warned about, omitted, and NOT installed —
    a second run still reports it missing (store untouched). Exit stays 0 so the
    prompt is never broken."""
    project = _make_locked_unpulled_project(ocx, tmp_path, "export_nopull")

    result = _run_export(ocx, project, "--no-pull")
    assert result.returncode == 0, f"expected exit 0; stderr:\n{result.stderr}"
    assert "not installed" in result.stderr, (
        f"missing-tool note expected on stderr\nstderr:\n{result.stderr}"
    )
    assert "export" not in result.stdout, (
        f"unmaterialised tool must be omitted\nstdout:\n{result.stdout}"
    )

    again = _run_export(ocx, project, "--no-pull")
    assert again.returncode == 0, again.stderr
    assert "not installed" in again.stderr, (
        f"--no-pull must never materialise the tool\nstderr:\n{again.stderr}"
    )
