# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The OCX Authors
"""Acceptance tests for ``ocx generate direnv`` (plan Phase 8).

These tests cover the three contract bullets at plan lines 822-824:

- ``ocx generate direnv`` -> creates ``.envrc`` with the spec content
- ``ocx generate direnv`` when ``.envrc`` exists -> exit 78 (ConfigError),
  preserve user content
- ``ocx generate direnv --force`` when ``.envrc`` exists -> overwrites

We bypass ``OcxRunner.run`` because the generator writes to CWD, and the
runner does not expose a ``cwd=`` parameter (same pattern as
``test_lock.py`` / ``test_project_pull.py``).
"""
from __future__ import annotations

import subprocess
from pathlib import Path

from src.runner import OcxRunner


# Exit code constant - matches crates/ocx_lib/src/cli/exit_code.rs::ExitCode::ConfigError
EXIT_CONFIG = 78


# Spec content from plan_project_toolchain.md lines 813-818.
# Constructed by concatenation rather than a single triple-quoted literal so
# the trailing-newline contract on each line is unambiguous.
EXPECTED_ENVRC = (
    "# Generated by ocx — run 'direnv allow' to activate\n"
    "# Requires: direnv (https://direnv.net)\n"
    "watch_file ocx.toml ocx.lock\n"
    'eval "$(ocx shell-hook --shell bash)"\n'
)


def _run_generate_direnv(
    ocx: OcxRunner,
    cwd: Path,
    *extra: str,
) -> subprocess.CompletedProcess[str]:
    """Run ``ocx generate direnv`` from ``cwd``.

    Bypasses ``OcxRunner.run`` to set the working directory: the command
    writes ``.envrc`` to CWD, so test isolation requires CWD = tmp_path.
    """
    cmd = [str(ocx.binary), "generate", "direnv", *extra]
    return subprocess.run(
        cmd,
        cwd=cwd,
        capture_output=True,
        text=True,
        env=ocx.env,
    )


def test_generate_direnv_creates_envrc(ocx: OcxRunner, tmp_path: Path) -> None:
    """Fresh project dir -> .envrc written with the spec content; exit 0."""
    result = _run_generate_direnv(ocx, tmp_path)
    assert result.returncode == 0, (
        f"expected exit 0; got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    envrc = tmp_path / ".envrc"
    assert envrc.exists(), "expected .envrc to be created"
    assert envrc.read_text() == EXPECTED_ENVRC


def test_generate_direnv_refuses_when_envrc_exists(
    ocx: OcxRunner, tmp_path: Path
) -> None:
    """Existing .envrc -> exit 78 (ConfigError); existing file untouched."""
    envrc = tmp_path / ".envrc"
    envrc.write_text("user content\n")
    result = _run_generate_direnv(ocx, tmp_path)
    assert result.returncode == EXIT_CONFIG, (
        f"expected ConfigError ({EXIT_CONFIG}) when .envrc exists; "
        f"got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert envrc.read_text() == "user content\n", (
        "user content must be preserved without --force"
    )


def test_generate_direnv_force_overwrites(
    ocx: OcxRunner, tmp_path: Path
) -> None:
    """Existing .envrc + --force -> overwritten with spec content; exit 0."""
    envrc = tmp_path / ".envrc"
    envrc.write_text("user content\n")
    result = _run_generate_direnv(ocx, tmp_path, "--force")
    assert result.returncode == 0, (
        f"expected exit 0 with --force; got {result.returncode}\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )
    assert envrc.read_text() == EXPECTED_ENVRC
