// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OCX Authors

//! Launcher body templates (Unix `.sh`) and the Windows `.shim` sidecar body.
//!
//! Body output is byte-stable per `adr_package_entry_points.md` — every
//! literal substring is a One-Way Door commitment covered by the golden tests
//! at the bottom of this file.
//!
//! Two wire vocabularies live here, one per kind of generated body:
//!
//! - `launcher exec` + the positional shape `<pkg-root> -- <argv0> [args...]`
//!   — the launcher an *installed* package's entry points get.
//! - `launcher shim` + the positional shape `<pinned-id> -- <argv0> [args...]`
//!   — the shim a *deferred* tool's declared names get, which materializes the
//!   package on first invocation.
//!
//! Both are ABI: all presentation flags, self-view selection, and OCX binary
//! pinning are hidden inside the subcommand, so bodies on disk are decoupled
//! from future evolutions of those internals.
//!
//! Windows no longer emits a `.cmd` launcher: the native `.exe` shim
//! (`crates/ocx_shim`) is the sole Windows launcher and reads the one-line
//! [`shim_sidecar_body`] sidecar to learn `pkg_root`. The shim is the second
//! producer of the frozen `launcher exec` wire string (the `.sh` body is the
//! first); see `subsystem-package-manager.md` "Wire-ABI canary rule".

use super::safety::LauncherSafeString;

/// Produces the body of a Unix `.sh` launcher.
///
/// The launcher bakes only `<pkg_root>` and calls
/// `ocx launcher exec '<pkg_root>' -- "$(basename "$0")" "$@"`, which reads
/// `metadata.json` from that root, composes the runtime env, and resolves the
/// entrypoint name against the composed `PATH` at invocation time. No binary
/// path is baked into the launcher body itself.
///
/// `${OCX_BINARY_PIN:-ocx}` pins the inner ocx to the binary that installed
/// the package (set by the outer ocx via `Env::apply_ocx_config`),
/// falling back to `$PATH` lookup when the launcher is invoked outside an
/// outer ocx (manual call, scripts, etc.).
///
/// All presentation flags and self-view selection are hidden inside
/// `launcher exec` — they are no longer baked into individual launchers.
///
/// Inputs are pre-validated [`LauncherSafeString`]s so this function is total
/// (no `Result`); the unsafe-char check fires once, at the [`super::generate`]
/// entry boundary, instead of being repeated per platform.
pub(super) fn unix_launcher_body(pkg_root: &LauncherSafeString) -> String {
    let pkg_root = pkg_root.as_str();
    // `$(basename "$0")` injects the launcher's own filename as argv0 after
    // `--`. `ocx launcher exec` receives the entrypoint name via argv0 and
    // resolves the binary against the composed `PATH` from the package's `env`
    // block — no binary path is baked into the launcher.
    //
    // `${OCX_BINARY_PIN:-ocx}` pins the inner ocx to the binary that installed
    // the package (set by the outer ocx via `Env::apply_ocx_config`),
    // falling back to `$PATH` lookup when the launcher is invoked outside an
    // outer ocx (manual call, scripts, etc.).
    //
    // The `launcher exec` subcommand internally forces presentation flags
    // (--log-level=off --color=never --format=plain) and self-view — these
    // are no longer baked into the launcher template.
    format!(
        "#!/bin/sh\n\
         # Generated by ocx at install time. Do not edit.\n\
         exec \"${{OCX_BINARY_PIN:-ocx}}\" launcher exec '{pkg_root}' -- \"$(basename \"$0\")\" \"$@\"\n"
    )
}

/// Produces the body of a Unix shim for one declared name of a **deferred**
/// tool — a tool composed onto `PATH` without its content being materialized.
///
/// The sibling of [`unix_launcher_body`], and deliberately shaped like it:
/// `${OCX_BINARY_PIN:-ocx}` pins the inner ocx, `$(basename "$0")` injects the
/// invoked name as `argv0` after `--`, and `"$@"` forwards the user's args.
/// The one difference is what is baked and which verb consumes it — a
/// **pinned identifier** and `launcher shim`, not a package root and
/// `launcher exec`. There is no package root to bake yet: the whole point of a
/// shim is that no package directory exists until it runs.
///
/// The body carries no report or mode token by design. `lazy-report` governs
/// what the materialization renders, and that decision belongs to the process
/// doing the download — freezing a compose-time value into the body would make
/// a generated shim answer for a setting the user changed since.
///
/// `identifier` is the pre-validated rendering of an
/// [`crate::oci::PinnedIdentifier`]. Taking a [`LauncherSafeString`] rather
/// than the identifier itself keeps the unsafe-character check at the
/// generator's entry boundary — one validator for every generated body — and
/// keeps this function total, exactly as [`unix_launcher_body`] is.
// Reached from outside this module through [`super::shim_body`], which owns
// the `LauncherSafeString` boundary so the generation task
// (`package_manager::tasks::prepare_lazy`) never handles a raw template.
pub(super) fn unix_shim_body(identifier: &LauncherSafeString) -> String {
    let identifier = identifier.as_str();
    // Mirrors `unix_launcher_body` line for line, including the
    // `# Generated by ocx at install time.` wording: the two bodies sit side by
    // side in `bin/` directories a user greps together, and one comment is
    // easier to recognize than two. Only the verb and the baked value differ.
    //
    // The `launcher shim` literal lives here and is restated independently by
    // `launcher_shim_wire_token_is_bound_to_shim_producer` below — never a
    // shared constant, which would make that canary unable to go red.
    format!(
        "#!/bin/sh\n\
         # Generated by ocx at install time. Do not edit.\n\
         exec \"${{OCX_BINARY_PIN:-ocx}}\" launcher shim '{identifier}' -- \"$(basename \"$0\")\" \"$@\"\n"
    )
}

/// Produces the body of a Windows `.shim` sidecar.
///
/// Contract: exactly the absolute `pkg_root` followed by a single `\n`
/// (LF), UTF-8 with no BOM. This is the One-Way-Door on-disk artifact the
/// native `ocx-shim.exe` reads to learn `pkg_root`; its byte/encoding spec is
/// frozen (see `adr_windows_exe_shim.md` §`.shim` Sidecar Format Contract).
/// Inputs are pre-validated [`LauncherSafeString`]s — see [`unix_launcher_body`].
// Only called from the cfg(windows) branch of `generate`; allow the dead_code
// lint so non-Windows builds stay clean (same pattern as
// `child_process::propagate_exit_status`).
#[cfg_attr(not(windows), allow(dead_code))]
pub(super) fn shim_sidecar_body(pkg_root: &LauncherSafeString) -> String {
    // Exactly `<pkg_root>\n` — LF only, no BOM, no CRLF, pkg_root and nothing
    // else. `pkg_root` is the already-validated `LauncherSafeString` (the
    // `LAUNCHER_UNSAFE_CHARS` guard ran at the `generate` entry boundary);
    // there is no second validator here (ADR Contract 2 / §`.shim` format).
    format!("{}\n", pkg_root.as_str())
}

#[cfg(test)]
mod tests {
    use super::super::safety::LauncherSafeString;

    fn safe(s: &str) -> LauncherSafeString {
        LauncherSafeString::new(s).unwrap()
    }

    // ── Unix launcher body — golden match ─────────────────────────────────

    #[test]
    fn unix_launcher_body_golden_match() {
        let body = super::unix_launcher_body(&safe("/some/pkg/root"));
        assert!(body.starts_with("#!/bin/sh"), "must start with shebang: {body}");
        assert!(
            body.contains("launcher exec '/some/pkg/root'"),
            "must inline single-quoted pkg_root for launcher exec: {body}"
        );
        assert!(
            body.contains("\"${OCX_BINARY_PIN:-ocx}\""),
            "must invoke the inner ocx via `${{OCX_BINARY_PIN:-ocx}}` (outer ocx pin + PATH fallback): {body}"
        );
        assert!(
            body.contains("\"$(basename \"$0\")\""),
            "must inject launcher's own filename via $(basename \"$0\"): {body}"
        );
        assert!(body.contains("\"$@\""), "must forward all args via \"$@\": {body}");
        assert!(
            !body.contains("_target"),
            "ADR §6: launcher must not bake `_target` (target resolved by `ocx exec` at invocation time): {body}"
        );
        assert!(
            !body.contains("file://"),
            "new launcher must not use file:// URI scheme (removed in favour of launcher exec): {body}"
        );
        // Presentation flags are no longer baked into the launcher template —
        // they are hidden inside `launcher exec` subcommand. Verify absence.
        assert!(
            !body.contains("--log-level=off"),
            "presentation flags must not be baked into launcher template: {body}"
        );
        assert!(
            !body.contains("--self"),
            "launcher must not bake --self directly; launcher exec handles self-view internally: {body}"
        );
    }

    // ── Path with spaces is handled correctly ─────────────────────────────

    #[test]
    fn unix_launcher_body_handles_path_with_spaces() {
        // Paths with spaces must be preserved verbatim inside single quotes.
        let body = super::unix_launcher_body(&safe("/path with spaces"));
        assert!(body.contains("spaces"), "space must appear in body: {body}");
    }

    // ── Byte-exact golden tests (One-Way Door wire-vocabulary) ─────────────

    /// ADR §6 invariant — no `_target` baked. The launcher passes its OWN
    /// filename via `$(basename "$0")` as argv0 after `--`, then forwards
    /// `"$@"` for user args. `ocx launcher exec` resolves the binary via the
    /// package's PATH env (set up from metadata).
    #[test]
    fn unix_launcher_body_byte_exact_match_adr_form() {
        let body = super::unix_launcher_body(&safe("/some/pkg/root"));
        // The stable wire surface is: `launcher exec '<pkg_root>' --` pair.
        // `${OCX_BINARY_PIN:-ocx}` is the pin expression (renamed from OCX_BINARY).
        let expected = "#!/bin/sh\n\
                        # Generated by ocx at install time. Do not edit.\n\
                        exec \"${OCX_BINARY_PIN:-ocx}\" launcher exec '/some/pkg/root' -- \"$(basename \"$0\")\" \"$@\"\n";
        assert_eq!(
            body, expected,
            "Unix launcher must match the byte-exact form (launcher exec subcommand; OCX_BINARY_PIN pin; no file://; no --self baked; no presentation flags baked)",
        );
    }

    // ── One-Way Door wire-vocabulary commitments ───────────────────────────
    //
    // The `launcher exec` subcommand name pair is the stable wire surface.
    // These tests are the canary — they fail loudly if the wire string drifts.

    #[test]
    fn launcher_unix_byte_format_locks_launcher_exec() {
        let body = super::unix_launcher_body(&safe("/x"));
        assert!(
            body.contains("launcher exec"),
            "Unix launcher must contain literal `launcher exec` (One-Way Door wire-vocabulary): {body}"
        );
    }

    /// Wire-ABI canary — TWO producers, both must agree. After the `.cmd`
    /// cutover the frozen `launcher exec` wire string has exactly two
    /// producers: the `.sh` body (`unix_launcher_body`, here) and the native
    /// Windows `.exe` shim (`crates/ocx_shim/src/core.rs`,
    /// `core::WIRE_SUBCOMMAND`) (`subsystem-package-manager.md` canary rule;
    /// `adr_windows_exe_shim.md` §"Wire-ABI Parity"). `ocx_lib` cannot depend
    /// on the `ocx_shim` binary crate, so the binding is a PAIRED GOLDEN:
    /// this restates the exact subcommand token the shim's
    /// `core::WIRE_SUBCOMMAND` must equal from the `.sh` side, and the shim's
    /// `tests::shim_wire_token_matches_sh_body` restates it from the shim
    /// side. A change to the wire vocabulary must touch BOTH this constant
    /// and `crates/ocx_shim/src/core.rs` `WIRE_SUBCOMMAND`, or one of the two
    /// canaries fails loudly.
    #[test]
    fn launcher_wire_token_is_bound_to_shim_producer() {
        // The exact `<launcher exec> '<pkg_root>'` shape the `.sh` body emits
        // — the shim's `core::WIRE_SUBCOMMAND` (= "launcher exec") must
        // reproduce this same token (see the cross-ref above).
        const SHARED_WIRE_SUBCOMMAND: &str = "launcher exec";
        let sh_body = super::unix_launcher_body(&safe("/pkg/root"));
        assert!(
            sh_body.contains(&format!("{SHARED_WIRE_SUBCOMMAND} '/pkg/root'")),
            "the `.sh` body must carry the shared `launcher exec '<pkg_root>'` token \
             (must stay in sync with `crates/ocx_shim/src/core.rs` WIRE_SUBCOMMAND): {sh_body}"
        );
    }

    // ── Unix shim body — byte-exact golden (C-010) ────────────────────────
    //
    // The shim body a *deferred* tool's declared names get. Written from
    // C-010 plus its 2026-08-10 amendment, which fixes the golden as the
    // WHOLE FILE mirroring `unix_launcher_body` — shebang, the same
    // `# Generated by ocx…` comment verbatim, the `exec` line, one trailing
    // LF. A body without a shebang is not executable via `execve` at all, so
    // the first line is contract, not decoration.

    /// The pinned identifier a generated shim bakes. Tag-bearing on purpose:
    /// C-010's amendment keeps the advisory tag, so the golden must carry one
    /// or it cannot distinguish "kept" from "stripped".
    const PINNED: &str =
        "ocx.sh/tool/cmake:3.28@sha256:0000000000000000000000000000000000000000000000000000000000000001";

    #[test]
    fn unix_shim_body_byte_exact_golden() {
        let body = super::unix_shim_body(&safe(PINNED));
        let expected = "#!/bin/sh\n\
                        # Generated by ocx at install time. Do not edit.\n\
                        exec \"${OCX_BINARY_PIN:-ocx}\" launcher shim \
                        'ocx.sh/tool/cmake:3.28@sha256:0000000000000000000000000000000000000000000000000000000000000001' \
                        -- \"$(basename \"$0\")\" \"$@\"\n";
        assert_eq!(
            body, expected,
            "the shim body is a byte-exact golden: shebang, the generated-by comment verbatim, \
             the `launcher shim` exec line, and exactly one trailing LF"
        );
    }

    /// The shebang and the single trailing LF, called out separately from the
    /// golden because their failure modes are the ones a reader of C-010's
    /// one-line `exec` statement would not think to check: no shebang means
    /// `execve` refuses the file outright, and a second LF is invisible in a
    /// diff.
    #[test]
    fn unix_shim_body_starts_with_a_shebang_and_ends_with_exactly_one_lf() {
        let body = super::unix_shim_body(&safe(PINNED));
        assert!(
            body.starts_with("#!/bin/sh\n"),
            "a body without a shebang is not executable via execve: {body:?}"
        );
        assert!(body.ends_with('\n'), "body must end with a single LF: {body:?}");
        assert!(!body.ends_with("\n\n"), "body must not end with two LFs: {body:?}");
        assert!(!body.contains('\r'), "terminators are LF only, never CRLF: {body:?}");
        assert_eq!(
            body.lines().count(),
            3,
            "the body is exactly three lines - shebang, comment, exec: {body:?}"
        );
    }

    /// The baked value is the pinned identifier verbatim, advisory tag
    /// included, single-quoted exactly as `unix_launcher_body` quotes its
    /// package root. Reds on a body that normalizes, strips or re-quotes what
    /// it was handed.
    #[test]
    fn unix_shim_body_bakes_the_pinned_identifier_verbatim_inside_single_quotes() {
        let body = super::unix_shim_body(&safe(PINNED));
        assert!(
            body.contains(&format!("'{PINNED}'")),
            "the identifier must appear verbatim inside single quotes, tag and all: {body}"
        );
        // Same function, tagless input: the body carries whatever it is given
        // and applies no shape rule of its own. Without this row the test
        // above would also pass for a body that hard-codes one fixture.
        let tagless = "ghcr.io/acme/tool@sha256:0000000000000000000000000000000000000000000000000000000000000002";
        assert!(
            super::unix_shim_body(&safe(tagless)).contains(&format!("'{tagless}'")),
            "a tagless pinned identifier is baked verbatim too"
        );
    }

    /// C-010: the body carries no report or mode token. `lazy-report` is
    /// resolved by the process that performs the download, so freezing a
    /// compose-time value into the body would make a generated shim answer
    /// for a setting the user has since changed.
    ///
    /// The positive assertion is not decoration: a set of `!contains` claims
    /// alone passes trivially against an empty string.
    #[test]
    fn unix_shim_body_carries_no_report_or_mode_token() {
        let body = super::unix_shim_body(&safe(PINNED));
        assert!(
            body.contains("launcher shim"),
            "control: the body must carry the wire verb, or every absence below is vacuous: {body}"
        );
        for token in ["lazy-report", "lazy-mode", "silent", "progress", "always", "never"] {
            assert!(
                !body.contains(token),
                "the shim body must bake no policy token; found '{token}': {body}"
            );
        }
    }

    /// Wire-ABI canary for the SECOND verb — the sibling of
    /// [`launcher_wire_token_is_bound_to_shim_producer`] (C-018).
    ///
    /// `ocx_lib` cannot depend on the `ocx_shim` binary crate, so the two
    /// producers of `launcher shim` are bound only by a paired golden: this
    /// restates the exact token from the `.sh` side, and the native shim's own
    /// test restates it from `crates/ocx_shim/src/core.rs` (WP-11's half).
    /// The constant is declared INSIDE the test on purpose — a production
    /// constant shared by body and canary would make the canary
    /// self-referential and unable to go red on a body change.
    #[test]
    fn launcher_shim_wire_token_is_bound_to_shim_producer() {
        const SHARED_WIRE_SUBCOMMAND: &str = "launcher shim";
        let sh_body = super::unix_shim_body(&safe("ocx.sh/x@sha256:00"));
        assert!(
            sh_body.contains(&format!("{SHARED_WIRE_SUBCOMMAND} 'ocx.sh/x@sha256:00'")),
            "the shim `.sh` body must carry the shared `launcher shim '<pinned-id>'` token \
             (must stay in sync with the native shim's WIRE_SUBCOMMAND for this verb): {sh_body}"
        );
    }

    /// The two generated bodies must not share a verb. This is the drift the
    /// paired goldens above cannot catch on their own: a shim body
    /// copy-pasted from the launcher body keeps `launcher exec`, still
    /// contains a plausible wire token, and silently dispatches a deferred
    /// tool into the verb that assumes its package already exists.
    #[test]
    fn each_generated_body_carries_exactly_its_own_verb() {
        let launcher = super::unix_launcher_body(&safe("/some/pkg/root"));
        let shim = super::unix_shim_body(&safe(PINNED));

        assert!(launcher.contains("launcher exec"), "launcher body keeps its verb");
        assert!(
            !launcher.contains("launcher shim"),
            "the installed-package launcher must never carry the shim verb: {launcher}"
        );
        assert!(shim.contains("launcher shim"), "shim body keeps its verb");
        assert!(
            !shim.contains("launcher exec"),
            "the deferred-tool shim must never carry the exec verb: {shim}"
        );
    }

    /// The shim mirrors the launcher on everything except the verb and the
    /// baked value: same pin expression, same argv0 injection, same
    /// forwarding. Named separately from the golden so a reader sees which
    /// substrings are shared ABI rather than incidental formatting.
    #[test]
    fn unix_shim_body_mirrors_the_launcher_pin_and_argv0_conventions() {
        let body = super::unix_shim_body(&safe(PINNED));
        assert!(
            body.contains("\"${OCX_BINARY_PIN:-ocx}\""),
            "must invoke the inner ocx via `${{OCX_BINARY_PIN:-ocx}}`: {body}"
        );
        assert!(
            body.contains("\"$(basename \"$0\")\""),
            "must inject the invoked name via $(basename \"$0\") after `--`: {body}"
        );
        assert!(body.contains(" -- "), "argv0 must follow a `--` separator: {body}");
        assert!(body.contains("\"$@\""), "must forward user args via \"$@\": {body}");
    }

    // ── `.shim` sidecar body golden ───────────────────────────────────────
    //
    // The `.shim` sidecar is the One-Way-Door on-disk artifact the native
    // `ocx-shim.exe` reads to learn `pkg_root`. Its byte/encoding spec is
    // frozen (`adr_windows_exe_shim.md` §`.shim` Sidecar Format Contract;
    // `system_design_windows_exe_shim.md` §6): exactly
    // `format!("{pkg_root}\n")` — UTF-8, no BOM, a single trailing LF, the
    // body is `pkg_root` and nothing else, never CRLF. These tests are
    // DAMP/self-contained peers of the `.sh` golden above and pin the exact
    // bytes so any drift fails loudly. They run on all hosts
    // (`shim_sidecar_body` is not Win32-gated).

    #[test]
    fn shim_sidecar_body_byte_exact_golden() {
        let body = super::shim_sidecar_body(&safe("C:\\Users\\ci\\.ocx\\packages\\ocx.sh\\sha256\\ab\\cd"));
        assert_eq!(
            body, "C:\\Users\\ci\\.ocx\\packages\\ocx.sh\\sha256\\ab\\cd\n",
            "sidecar must be exactly `format!(\"{{pkg_root}}\\n\")` — pkg_root then a single LF"
        );
    }

    #[test]
    fn shim_sidecar_body_is_utf8_without_bom() {
        let body = super::shim_sidecar_body(&safe("C:\\pkg\\root"));
        assert!(
            !body.starts_with('\u{feff}') && !body.as_bytes().starts_with(&[0xEF, 0xBB, 0xBF]),
            "sidecar must not be prefixed with a UTF-8 BOM (EF BB BF): {body:?}"
        );
    }

    #[test]
    fn shim_sidecar_body_has_single_trailing_lf_no_crlf() {
        let body = super::shim_sidecar_body(&safe("C:\\pkg\\root"));
        assert!(body.ends_with('\n'), "sidecar must end with a single LF: {body:?}");
        assert!(
            !body.ends_with("\r\n"),
            "sidecar terminator must be LF only, never CRLF: {body:?}"
        );
        assert!(
            !body.ends_with("\n\n"),
            "sidecar must have exactly one trailing LF, not two: {body:?}"
        );
        assert_eq!(
            body.matches('\n').count(),
            1,
            "sidecar must contain exactly one LF (the terminator): {body:?}"
        );
    }

    #[test]
    fn shim_sidecar_body_is_pkg_root_only() {
        // Body == pkg_root + LF and nothing else (no comment, no shebang, no
        // wire vocabulary — unlike the `.sh` launcher, the sidecar carries
        // ONLY the package root; the shim re-invokes `launcher exec`).
        let body = super::shim_sidecar_body(&safe("C:\\pkg\\root"));
        assert_eq!(
            body.strip_suffix('\n'),
            Some("C:\\pkg\\root"),
            "stripping the single LF must leave exactly pkg_root: {body:?}"
        );
        assert!(
            !body.contains("launcher exec"),
            "sidecar must NOT carry wire vocabulary — only pkg_root: {body:?}"
        );
        assert!(
            !body.contains('\r') && !body.contains('\0'),
            "sidecar body must not contain CR or NUL: {body:?}"
        );
    }
}
