// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OCX Authors

//! Launcher body templates (Unix `.sh` and Windows `.cmd`).
//!
//! Body output is byte-stable per `adr_package_entry_points.md` — every
//! literal substring is a One-Way Door commitment covered by the golden tests
//! at the bottom of this file.
//!
//! The stable ABI surface is exactly two commitments: the `launcher exec`
//! subcommand name pair and the positional shape `<pkg-root> -- <argv0> [args...]`.
//! All presentation flags, self-view selection, and OCX binary pinning are
//! hidden inside the `launcher exec` subcommand — launchers on disk are
//! decoupled from future evolutions of those internals.

use super::safety::LauncherSafeString;

/// Produces the body of a Unix `.sh` launcher.
///
/// Per ADR `adr_package_entry_points.md` §6, the launcher does NOT bake the
/// resolved `target` — `target` is a publish-time existence assertion only.
/// The launcher calls `ocx launcher exec '<pkg_root>' -- "$(basename "$0")" "$@"`,
/// which reads `metadata.json` from that root and resolves the target via env
/// interpolation at invocation time.
///
/// `${OCX_BINARY_PIN:-ocx}` pins the inner ocx to the binary that installed
/// the package (set by the outer ocx via `Env::apply_ocx_config`),
/// falling back to `$PATH` lookup when the launcher is invoked outside an
/// outer ocx (manual call, scripts, etc.).
///
/// All presentation flags and self-view selection are hidden inside
/// `launcher exec` — they are no longer baked into individual launchers.
///
/// Inputs are pre-validated [`LauncherSafeString`]s so this function is total
/// (no `Result`); the unsafe-char check fires once, at the [`super::generate`]
/// entry boundary, instead of being repeated per platform.
pub(super) fn unix_launcher_body(pkg_root: &LauncherSafeString) -> String {
    let pkg_root = pkg_root.as_str();
    // `$(basename "$0")` injects the launcher's own filename as argv0 after
    // `--`. ADR §6 invariant ("target field is not the launcher file") is
    // preserved: nothing from `target` is baked. `ocx launcher exec` receives
    // the entrypoint name via argv0 and resolves the binary through the
    // package's PATH env (set up from metadata).
    //
    // `${OCX_BINARY_PIN:-ocx}` pins the inner ocx to the binary that installed
    // the package (set by the outer ocx via `Env::apply_ocx_config`),
    // falling back to `$PATH` lookup when the launcher is invoked outside an
    // outer ocx (manual call, scripts, etc.).
    //
    // The `launcher exec` subcommand internally forces presentation flags
    // (--log-level=off --color=never --format=plain) and self-view — these
    // are no longer baked into the launcher template.
    format!(
        "#!/bin/sh\n\
         # Generated by ocx at install time. Do not edit.\n\
         exec \"${{OCX_BINARY_PIN:-ocx}}\" launcher exec '{pkg_root}' -- \"$(basename \"$0\")\" \"$@\"\n"
    )
}

/// Produces the body of a Windows `.cmd` launcher.
///
/// Per ADR `adr_package_entry_points.md` §6, the launcher does NOT bake the
/// resolved `target` — `target` is a publish-time existence assertion only.
/// The launcher calls `ocx launcher exec "<pkg_root>" -- "%~n0" %*`,
/// which reads `metadata.json` from that root and resolves the target via env
/// interpolation at invocation time.
///
/// `SETLOCAL DisableDelayedExpansion` closes the registry-level `!VAR!`
/// expansion vector (BatBadBut interim mitigation, ADR
/// `adr_windows_cmd_argv_injection.md`). Residual risk: caller-supplied
/// arguments forwarded via `%*` are still re-parsed by `cmd.exe`; callers
/// passing user-controlled argument strings must shell-quote them.
///
/// `EXIT /B %ERRORLEVEL%` after the IF/ELSE block is load-bearing: cmd.exe
/// has no `exec` equivalent, so the inner ocx exit code must be propagated
/// explicitly. Without it, propagation depends on cmd.exe's implicit
/// end-of-script behaviour, which interacts subtly with `SETLOCAL` and
/// parenthesised `IF/ELSE` blocks. The Unix template gets the same property
/// for free via `exec`.
///
/// Inputs are pre-validated [`LauncherSafeString`]s — see [`unix_launcher_body`].
pub(super) fn windows_launcher_body(pkg_root: &LauncherSafeString) -> String {
    let pkg_root = pkg_root.as_str();
    // `%~n0` expands to the script's filename without path or extension —
    // identical role to Unix `$(basename "$0")`. ADR §6 invariant preserved:
    // nothing from `target` is baked.
    // `DisableDelayedExpansion`: closes the `!VAR!` expansion vector that is
    // active when the Windows registry key
    // `HKCU\Software\Microsoft\Command Processor\DelayedExpansion` is set to
    // `1`. See ADR `adr_windows_cmd_argv_injection.md` for threat model.
    //
    // `IF DEFINED OCX_BINARY_PIN` mirrors the Unix `${OCX_BINARY_PIN:-ocx}` form:
    // when set by an outer ocx (via `Env::apply_ocx_config`), the launcher
    // pins the inner ocx to the same binary; otherwise it falls through to
    // a `$PATH` lookup.
    //
    // `EXIT /B %ERRORLEVEL%` makes inner-ocx exit-code propagation explicit
    // (no cmd.exe `exec` equivalent — without this, propagation through the
    // `SETLOCAL` + parenthesised `IF/ELSE` block is interpreter-dependent).
    format!(
        "@ECHO off\n\
         SETLOCAL DisableDelayedExpansion\n\
         IF DEFINED OCX_BINARY_PIN (\n\
         \x20\x20\"%OCX_BINARY_PIN%\" launcher exec \"{pkg_root}\" -- \"%~n0\" %*\n\
         ) ELSE (\n\
         \x20\x20ocx launcher exec \"{pkg_root}\" -- \"%~n0\" %*\n\
         )\n\
         EXIT /B %ERRORLEVEL%\n"
    )
}

#[cfg(test)]
mod tests {
    use super::super::safety::LauncherSafeString;

    fn safe(s: &str) -> LauncherSafeString {
        LauncherSafeString::new(s).unwrap()
    }

    // ── Unix launcher body — golden match ─────────────────────────────────

    #[test]
    fn unix_launcher_body_golden_match() {
        let body = super::unix_launcher_body(&safe("/some/pkg/root"));
        assert!(body.starts_with("#!/bin/sh"), "must start with shebang: {body}");
        assert!(
            body.contains("launcher exec '/some/pkg/root'"),
            "must inline single-quoted pkg_root for launcher exec: {body}"
        );
        assert!(
            body.contains("\"${OCX_BINARY_PIN:-ocx}\""),
            "must invoke the inner ocx via `${{OCX_BINARY_PIN:-ocx}}` (outer ocx pin + PATH fallback): {body}"
        );
        assert!(
            body.contains("\"$(basename \"$0\")\""),
            "must inject launcher's own filename via $(basename \"$0\"): {body}"
        );
        assert!(body.contains("\"$@\""), "must forward all args via \"$@\": {body}");
        assert!(
            !body.contains("_target"),
            "ADR §6: launcher must not bake `_target` (target resolved by `ocx exec` at invocation time): {body}"
        );
        assert!(
            !body.contains("file://"),
            "new launcher must not use file:// URI scheme (removed in favour of launcher exec): {body}"
        );
        // Presentation flags are no longer baked into the launcher template —
        // they are hidden inside `launcher exec` subcommand. Verify absence.
        assert!(
            !body.contains("--log-level=off"),
            "presentation flags must not be baked into launcher template: {body}"
        );
        assert!(
            !body.contains("--self"),
            "launcher must not bake --self directly; launcher exec handles self-view internally: {body}"
        );
    }

    #[test]
    fn windows_launcher_body_golden_match() {
        let body = super::windows_launcher_body(&safe("C:\\pkg\\root"));
        assert!(
            body.contains("@ECHO off") || body.contains("@echo off"),
            "must have ECHO off: {body}"
        );
        assert!(
            body.contains("SETLOCAL DisableDelayedExpansion"),
            "must have SETLOCAL DisableDelayedExpansion (BatBadBut interim mitigation): {body}"
        );
        assert!(
            body.contains("IF DEFINED OCX_BINARY_PIN"),
            "must branch on `IF DEFINED OCX_BINARY_PIN` to honour outer-ocx pin: {body}"
        );
        assert!(
            body.contains("\"%OCX_BINARY_PIN%\""),
            "must invoke inner ocx via `\"%OCX_BINARY_PIN%\"` when set: {body}"
        );
        assert!(
            body.contains("launcher exec \"C:\\pkg\\root\""),
            "must inline `launcher exec \"<pkg_root>\"`: {body}"
        );
        assert!(
            body.contains("\"%~n0\""),
            "must inject launcher's own filename via %~n0: {body}"
        );
        assert!(body.contains("%*"), "must forward all args via %*: {body}");
        assert!(
            body.contains("EXIT /B %ERRORLEVEL%"),
            "must propagate inner-ocx exit code via `EXIT /B %ERRORLEVEL%` (no cmd.exe exec equivalent): {body}"
        );
        assert!(
            !body.contains("_target"),
            "ADR §6: launcher must not bake `_target` (target resolved by `ocx exec` at invocation time): {body}"
        );
        assert!(
            !body.contains("file://"),
            "new launcher must not use file:// URI scheme (removed in favour of launcher exec): {body}"
        );
        // Presentation flags are no longer baked — hidden inside `launcher exec`.
        assert!(
            !body.contains("--log-level=off"),
            "presentation flags must not be baked into launcher template: {body}"
        );
        assert!(
            !body.contains("--self"),
            "launcher must not bake --self directly; launcher exec handles self-view internally: {body}"
        );
    }

    // ── Path with spaces is handled correctly ─────────────────────────────

    #[test]
    fn unix_launcher_body_handles_path_with_spaces() {
        // Paths with spaces must be preserved verbatim inside single quotes.
        let body = super::unix_launcher_body(&safe("/path with spaces"));
        assert!(body.contains("spaces"), "space must appear in body: {body}");
    }

    // ── Byte-exact golden tests (One-Way Door wire-vocabulary) ─────────────

    /// ADR §6 invariant — no `_target` baked. The launcher passes its OWN
    /// filename via `$(basename "$0")` as argv0 after `--`, then forwards
    /// `"$@"` for user args. `ocx launcher exec` resolves the binary via the
    /// package's PATH env (set up from metadata).
    #[test]
    fn unix_launcher_body_byte_exact_match_adr_form() {
        let body = super::unix_launcher_body(&safe("/some/pkg/root"));
        // The stable wire surface is: `launcher exec '<pkg_root>' --` pair.
        // `${OCX_BINARY_PIN:-ocx}` is the pin expression (renamed from OCX_BINARY).
        let expected = "#!/bin/sh\n\
                        # Generated by ocx at install time. Do not edit.\n\
                        exec \"${OCX_BINARY_PIN:-ocx}\" launcher exec '/some/pkg/root' -- \"$(basename \"$0\")\" \"$@\"\n";
        assert_eq!(
            body, expected,
            "Unix launcher must match the byte-exact form (launcher exec subcommand; OCX_BINARY_PIN pin; no file://; no --self baked; no presentation flags baked)",
        );
    }

    /// Windows launcher mirrors ADR §6 — no `_target` SET. `%~n0` injects
    /// the script's name without extension as argv0, then `%*` forwards user
    /// args. `DisableDelayedExpansion` closes the `!VAR!` vector (BatBadBut
    /// interim mitigation — ADR `adr_windows_cmd_argv_injection.md`).
    #[test]
    fn windows_launcher_body_byte_exact_match_adr_form() {
        let body = super::windows_launcher_body(&safe("C:\\pkg\\root"));
        // The stable wire surface is: `launcher exec "<pkg_root>" --` pair.
        // `OCX_BINARY_PIN` (renamed from `OCX_BINARY`) is the pin variable.
        let expected = "@ECHO off\n\
                        SETLOCAL DisableDelayedExpansion\n\
                        IF DEFINED OCX_BINARY_PIN (\n  \
                        \"%OCX_BINARY_PIN%\" launcher exec \"C:\\pkg\\root\" -- \"%~n0\" %*\n\
                        ) ELSE (\n  \
                        ocx launcher exec \"C:\\pkg\\root\" -- \"%~n0\" %*\n\
                        )\n\
                        EXIT /B %ERRORLEVEL%\n";
        assert_eq!(
            body, expected,
            "Windows launcher must match the byte-exact form (launcher exec subcommand; OCX_BINARY_PIN pin via IF DEFINED; explicit EXIT /B %ERRORLEVEL%; no file://; no --self baked; no presentation flags baked)",
        );
        assert!(
            body.contains("SETLOCAL DisableDelayedExpansion"),
            "launcher must use SETLOCAL DisableDelayedExpansion (BatBadBut interim mitigation): {body}"
        );
        assert!(
            !body.contains("EnableDelayedExpansion"),
            "template must not enable delayed expansion: {body}"
        );
    }

    /// Regression — `.cmd` launcher must terminate with `EXIT /B %ERRORLEVEL%`
    /// so the inner `ocx launcher exec` exit code propagates verbatim.
    /// cmd.exe has no `exec` equivalent (the Unix template gets this for free
    /// via `exec`); without explicit `EXIT /B` propagation through the
    /// `SETLOCAL` + parenthesised `IF/ELSE` block is interpreter-dependent.
    #[test]
    fn windows_launcher_body_propagates_exit_code() {
        let body = super::windows_launcher_body(&safe("C:\\pkg\\root"));
        assert!(
            body.contains("EXIT /B %ERRORLEVEL%"),
            "Windows launcher must end with explicit `EXIT /B %ERRORLEVEL%` to propagate inner-ocx exit code: {body}"
        );
        // Final non-empty line must be the EXIT — no commands after it that
        // could reset ERRORLEVEL before it is captured.
        let last = body.lines().rfind(|l| !l.trim().is_empty()).unwrap_or("");
        assert_eq!(
            last.trim(),
            "EXIT /B %ERRORLEVEL%",
            "EXIT /B %ERRORLEVEL% must be the final command in the script (nothing else can run after it that could overwrite ERRORLEVEL): last line was {last:?}",
        );
    }

    /// `.cmd` quoting property test — the Windows launcher body must not
    /// expand any cmd.exe metachars (`& ^ < > ! |`) outside double-quoted
    /// regions. The launcher's `LauncherSafeString` rejects unsafe characters
    /// at the entry boundary (via `LAUNCHER_UNSAFE_CHARS`), and the ADR §6
    /// form removes the resolved-target SET surface entirely — there must be
    /// no `_target=` SET line at all.
    ///
    /// `(` and `)` are intentionally NOT in the metachar list: the
    /// `IF DEFINED OCX_BINARY_PIN (` / `) ELSE (` / `)` structural block
    /// delimiters are template-baked, never derived from `pkg_root`.
    #[test]
    fn windows_launcher_body_no_unescaped_cmd_metachars() {
        let body = super::windows_launcher_body(&safe("C:\\pkg\\root"));
        // ADR §6 form: launcher must not bake _target at all (no SET _target line).
        assert!(
            !body.contains("_target"),
            "ADR §6 launcher must not bake `_target` SET — present in:\n{body}"
        );
        // Defensive check: nothing outside double-quoted regions should contain
        // cmd.exe metachars. We scan the body line-by-line and assert that each
        // metachar instance, if present, appears between a `"` pair.
        for (lineno, line) in body.lines().enumerate() {
            for &meta in &['&', '^', '<', '>', '!', '|'] {
                if let Some(idx) = line.find(meta) {
                    let before = &line[..idx];
                    let after = &line[idx + 1..];
                    let opens_before = before.matches('"').count();
                    let closes_after = after.matches('"').count();
                    let is_quoted = opens_before % 2 == 1 && closes_after >= 1;
                    assert!(
                        is_quoted,
                        "line {lineno}: unquoted cmd.exe metachar {meta:?} in launcher body:\n{line}",
                    );
                }
            }
        }
    }

    // ── One-Way Door wire-vocabulary commitments ───────────────────────────
    //
    // The `launcher exec` subcommand name pair is the stable wire surface.
    // These tests are the canary — they fail loudly if the wire string drifts.

    #[test]
    fn launcher_unix_byte_format_locks_launcher_exec() {
        let body = super::unix_launcher_body(&safe("/x"));
        assert!(
            body.contains("launcher exec"),
            "Unix launcher must contain literal `launcher exec` (One-Way Door wire-vocabulary): {body}"
        );
    }

    #[test]
    fn launcher_windows_byte_format_locks_launcher_exec() {
        let body = super::windows_launcher_body(&safe("C:\\x"));
        assert!(
            body.contains("launcher exec"),
            "Windows launcher must contain literal `launcher exec` (One-Way Door wire-vocabulary): {body}"
        );
    }
}
