// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OCX Authors

//! Launcher body templates (Unix `.sh`) and the Windows `.shim` sidecar body.
//!
//! Body output is byte-stable per `adr_package_entry_points.md` — every
//! literal substring is a One-Way Door commitment covered by the golden tests
//! at the bottom of this file.
//!
//! The stable ABI surface is exactly two commitments: the `launcher exec`
//! subcommand name pair and the positional shape `<pkg-root> -- <argv0> [args...]`.
//! All presentation flags, self-view selection, and OCX binary pinning are
//! hidden inside the `launcher exec` subcommand — launchers on disk are
//! decoupled from future evolutions of those internals.
//!
//! Windows no longer emits a `.cmd` launcher: the native `.exe` shim
//! (`crates/ocx_shim`) is the sole Windows launcher and reads the one-line
//! [`shim_sidecar_body`] sidecar to learn `pkg_root`. The shim is the second
//! producer of the frozen `launcher exec` wire string (the `.sh` body is the
//! first); see `subsystem-package-manager.md` "Wire-ABI canary rule".

use super::safety::LauncherSafeString;

/// Produces the body of a Unix `.sh` launcher.
///
/// The launcher bakes only `<pkg_root>` and calls
/// `ocx launcher exec '<pkg_root>' -- "$(basename "$0")" "$@"`, which reads
/// `metadata.json` from that root, composes the runtime env, and resolves the
/// entrypoint name against the composed `PATH` at invocation time. No binary
/// path is baked into the launcher body itself.
///
/// `${OCX_BINARY_PIN:-ocx}` pins the inner ocx to the binary that installed
/// the package (set by the outer ocx via `Env::apply_ocx_config`),
/// falling back to `$PATH` lookup when the launcher is invoked outside an
/// outer ocx (manual call, scripts, etc.).
///
/// All presentation flags and self-view selection are hidden inside
/// `launcher exec` — they are no longer baked into individual launchers.
///
/// Inputs are pre-validated [`LauncherSafeString`]s so this function is total
/// (no `Result`); the unsafe-char check fires once, at the [`super::generate`]
/// entry boundary, instead of being repeated per platform.
pub(super) fn unix_launcher_body(pkg_root: &LauncherSafeString) -> String {
    let pkg_root = pkg_root.as_str();
    // `$(basename "$0")` injects the launcher's own filename as argv0 after
    // `--`. `ocx launcher exec` receives the entrypoint name via argv0 and
    // resolves the binary against the composed `PATH` from the package's `env`
    // block — no binary path is baked into the launcher.
    //
    // `${OCX_BINARY_PIN:-ocx}` pins the inner ocx to the binary that installed
    // the package (set by the outer ocx via `Env::apply_ocx_config`),
    // falling back to `$PATH` lookup when the launcher is invoked outside an
    // outer ocx (manual call, scripts, etc.).
    //
    // The `launcher exec` subcommand internally forces presentation flags
    // (--log-level=off --color=never --format=plain) and self-view — these
    // are no longer baked into the launcher template.
    format!(
        "#!/bin/sh\n\
         # Generated by ocx at install time. Do not edit.\n\
         exec \"${{OCX_BINARY_PIN:-ocx}}\" launcher exec '{pkg_root}' -- \"$(basename \"$0\")\" \"$@\"\n"
    )
}

/// Produces the body of a Windows `.shim` sidecar.
///
/// Contract: exactly the absolute `pkg_root` followed by a single `\n`
/// (LF), UTF-8 with no BOM. This is the One-Way-Door on-disk artifact the
/// native `ocx-shim.exe` reads to learn `pkg_root`; its byte/encoding spec is
/// frozen (see `adr_windows_exe_shim.md` §`.shim` Sidecar Format Contract).
/// Inputs are pre-validated [`LauncherSafeString`]s — see [`unix_launcher_body`].
// Only called from the cfg(windows) branch of `generate`; allow the dead_code
// lint so non-Windows builds stay clean (same pattern as
// `child_process::propagate_exit_status`).
#[cfg_attr(not(windows), allow(dead_code))]
pub(super) fn shim_sidecar_body(pkg_root: &LauncherSafeString) -> String {
    // Exactly `<pkg_root>\n` — LF only, no BOM, no CRLF, pkg_root and nothing
    // else. `pkg_root` is the already-validated `LauncherSafeString` (the
    // `LAUNCHER_UNSAFE_CHARS` guard ran at the `generate` entry boundary);
    // there is no second validator here (ADR Contract 2 / §`.shim` format).
    format!("{}\n", pkg_root.as_str())
}

#[cfg(test)]
mod tests {
    use super::super::safety::LauncherSafeString;

    fn safe(s: &str) -> LauncherSafeString {
        LauncherSafeString::new(s).unwrap()
    }

    // ── Unix launcher body — golden match ─────────────────────────────────

    #[test]
    fn unix_launcher_body_golden_match() {
        let body = super::unix_launcher_body(&safe("/some/pkg/root"));
        assert!(body.starts_with("#!/bin/sh"), "must start with shebang: {body}");
        assert!(
            body.contains("launcher exec '/some/pkg/root'"),
            "must inline single-quoted pkg_root for launcher exec: {body}"
        );
        assert!(
            body.contains("\"${OCX_BINARY_PIN:-ocx}\""),
            "must invoke the inner ocx via `${{OCX_BINARY_PIN:-ocx}}` (outer ocx pin + PATH fallback): {body}"
        );
        assert!(
            body.contains("\"$(basename \"$0\")\""),
            "must inject launcher's own filename via $(basename \"$0\"): {body}"
        );
        assert!(body.contains("\"$@\""), "must forward all args via \"$@\": {body}");
        assert!(
            !body.contains("_target"),
            "ADR §6: launcher must not bake `_target` (target resolved by `ocx exec` at invocation time): {body}"
        );
        assert!(
            !body.contains("file://"),
            "new launcher must not use file:// URI scheme (removed in favour of launcher exec): {body}"
        );
        // Presentation flags are no longer baked into the launcher template —
        // they are hidden inside `launcher exec` subcommand. Verify absence.
        assert!(
            !body.contains("--log-level=off"),
            "presentation flags must not be baked into launcher template: {body}"
        );
        assert!(
            !body.contains("--self"),
            "launcher must not bake --self directly; launcher exec handles self-view internally: {body}"
        );
    }

    // ── Path with spaces is handled correctly ─────────────────────────────

    #[test]
    fn unix_launcher_body_handles_path_with_spaces() {
        // Paths with spaces must be preserved verbatim inside single quotes.
        let body = super::unix_launcher_body(&safe("/path with spaces"));
        assert!(body.contains("spaces"), "space must appear in body: {body}");
    }

    // ── Byte-exact golden tests (One-Way Door wire-vocabulary) ─────────────

    /// ADR §6 invariant — no `_target` baked. The launcher passes its OWN
    /// filename via `$(basename "$0")` as argv0 after `--`, then forwards
    /// `"$@"` for user args. `ocx launcher exec` resolves the binary via the
    /// package's PATH env (set up from metadata).
    #[test]
    fn unix_launcher_body_byte_exact_match_adr_form() {
        let body = super::unix_launcher_body(&safe("/some/pkg/root"));
        // The stable wire surface is: `launcher exec '<pkg_root>' --` pair.
        // `${OCX_BINARY_PIN:-ocx}` is the pin expression (renamed from OCX_BINARY).
        let expected = "#!/bin/sh\n\
                        # Generated by ocx at install time. Do not edit.\n\
                        exec \"${OCX_BINARY_PIN:-ocx}\" launcher exec '/some/pkg/root' -- \"$(basename \"$0\")\" \"$@\"\n";
        assert_eq!(
            body, expected,
            "Unix launcher must match the byte-exact form (launcher exec subcommand; OCX_BINARY_PIN pin; no file://; no --self baked; no presentation flags baked)",
        );
    }

    // ── One-Way Door wire-vocabulary commitments ───────────────────────────
    //
    // The `launcher exec` subcommand name pair is the stable wire surface.
    // These tests are the canary — they fail loudly if the wire string drifts.

    #[test]
    fn launcher_unix_byte_format_locks_launcher_exec() {
        let body = super::unix_launcher_body(&safe("/x"));
        assert!(
            body.contains("launcher exec"),
            "Unix launcher must contain literal `launcher exec` (One-Way Door wire-vocabulary): {body}"
        );
    }

    /// Wire-ABI canary — TWO producers, both must agree. After the `.cmd`
    /// cutover the frozen `launcher exec` wire string has exactly two
    /// producers: the `.sh` body (`unix_launcher_body`, here) and the native
    /// Windows `.exe` shim (`crates/ocx_shim/src/core.rs`,
    /// `core::WIRE_SUBCOMMAND`) (`subsystem-package-manager.md` canary rule;
    /// `adr_windows_exe_shim.md` §"Wire-ABI Parity"). `ocx_lib` cannot depend
    /// on the `ocx_shim` binary crate, so the binding is a PAIRED GOLDEN:
    /// this restates the exact subcommand token the shim's
    /// `core::WIRE_SUBCOMMAND` must equal from the `.sh` side, and the shim's
    /// `tests::shim_wire_token_matches_sh_body` restates it from the shim
    /// side. A change to the wire vocabulary must touch BOTH this constant
    /// and `crates/ocx_shim/src/core.rs` `WIRE_SUBCOMMAND`, or one of the two
    /// canaries fails loudly.
    #[test]
    fn launcher_wire_token_is_bound_to_shim_producer() {
        // The exact `<launcher exec> '<pkg_root>'` shape the `.sh` body emits
        // — the shim's `core::WIRE_SUBCOMMAND` (= "launcher exec") must
        // reproduce this same token (see the cross-ref above).
        const SHARED_WIRE_SUBCOMMAND: &str = "launcher exec";
        let sh_body = super::unix_launcher_body(&safe("/pkg/root"));
        assert!(
            sh_body.contains(&format!("{SHARED_WIRE_SUBCOMMAND} '/pkg/root'")),
            "the `.sh` body must carry the shared `launcher exec '<pkg_root>'` token \
             (must stay in sync with `crates/ocx_shim/src/core.rs` WIRE_SUBCOMMAND): {sh_body}"
        );
    }

    // ── `.shim` sidecar body golden ───────────────────────────────────────
    //
    // The `.shim` sidecar is the One-Way-Door on-disk artifact the native
    // `ocx-shim.exe` reads to learn `pkg_root`. Its byte/encoding spec is
    // frozen (`adr_windows_exe_shim.md` §`.shim` Sidecar Format Contract;
    // `system_design_windows_exe_shim.md` §6): exactly
    // `format!("{pkg_root}\n")` — UTF-8, no BOM, a single trailing LF, the
    // body is `pkg_root` and nothing else, never CRLF. These tests are
    // DAMP/self-contained peers of the `.sh` golden above and pin the exact
    // bytes so any drift fails loudly. They run on all hosts
    // (`shim_sidecar_body` is not Win32-gated).

    #[test]
    fn shim_sidecar_body_byte_exact_golden() {
        let body = super::shim_sidecar_body(&safe("C:\\Users\\ci\\.ocx\\packages\\ocx.sh\\sha256\\ab\\cd"));
        assert_eq!(
            body, "C:\\Users\\ci\\.ocx\\packages\\ocx.sh\\sha256\\ab\\cd\n",
            "sidecar must be exactly `format!(\"{{pkg_root}}\\n\")` — pkg_root then a single LF"
        );
    }

    #[test]
    fn shim_sidecar_body_is_utf8_without_bom() {
        let body = super::shim_sidecar_body(&safe("C:\\pkg\\root"));
        assert!(
            !body.starts_with('\u{feff}') && !body.as_bytes().starts_with(&[0xEF, 0xBB, 0xBF]),
            "sidecar must not be prefixed with a UTF-8 BOM (EF BB BF): {body:?}"
        );
    }

    #[test]
    fn shim_sidecar_body_has_single_trailing_lf_no_crlf() {
        let body = super::shim_sidecar_body(&safe("C:\\pkg\\root"));
        assert!(body.ends_with('\n'), "sidecar must end with a single LF: {body:?}");
        assert!(
            !body.ends_with("\r\n"),
            "sidecar terminator must be LF only, never CRLF: {body:?}"
        );
        assert!(
            !body.ends_with("\n\n"),
            "sidecar must have exactly one trailing LF, not two: {body:?}"
        );
        assert_eq!(
            body.matches('\n').count(),
            1,
            "sidecar must contain exactly one LF (the terminator): {body:?}"
        );
    }

    #[test]
    fn shim_sidecar_body_is_pkg_root_only() {
        // Body == pkg_root + LF and nothing else (no comment, no shebang, no
        // wire vocabulary — unlike the `.sh` launcher, the sidecar carries
        // ONLY the package root; the shim re-invokes `launcher exec`).
        let body = super::shim_sidecar_body(&safe("C:\\pkg\\root"));
        assert_eq!(
            body.strip_suffix('\n'),
            Some("C:\\pkg\\root"),
            "stripping the single LF must leave exactly pkg_root: {body:?}"
        );
        assert!(
            !body.contains("launcher exec"),
            "sidecar must NOT carry wire vocabulary — only pkg_root: {body:?}"
        );
        assert!(
            !body.contains('\r') && !body.contains('\0'),
            "sidecar body must not contain CR or NUL: {body:?}"
        );
    }
}
