// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OCX Authors

//! The two trampoline-identity cases whose fixtures are **generated launchers**.
//!
//! `is_ocx_trampoline` lives in `ocx_config::env`, and every other case for it is a
//! hand-written body beside that predicate. These two are not: they render the
//! real [`generate`](super::generate) and [`shim_body`](super::shim_body)
//! output, so the predicate is measured against the bytes this module actually
//! emits rather than an approximation of them. That makes the launcher the
//! subject and the predicate the assertion, which is why they sit here.

#![cfg(test)]

// Every item in this file is `#[cfg(unix)]` — the launcher bodies it renders are
// POSIX shell. Gating the imports too keeps the Windows build warning-clean.
#[cfg(unix)]
use std::path::PathBuf;

#[cfg(unix)]
use ocx_config::env::{TRAMPOLINE_MARKER, TRAMPOLINE_PROBE_BYTES, is_ocx_trampoline};

/// An executable POSIX body carrying [`TRAMPOLINE_MARKER`] on its second line,
/// exactly where C-028's generated trampoline puts it.
#[cfg(unix)]
fn write_trampoline(dir: &std::path::Path, name: &str) -> PathBuf {
    use std::os::unix::fs::PermissionsExt;
    let path = dir.join(name);
    std::fs::write(
        &path,
        format!(
            "#!/bin/sh\n{TRAMPOLINE_MARKER}\nunset OCX_GLOBAL OCX_PROJECT\n\
             __ocx_binary='/home/ocx/bin/ocx'\n\
             exec \"${{OCX_BINARY_PIN:-$__ocx_binary}}\" --project '/p' exec -- \"${{0##*/}}\" \"$@\"\n"
        ),
    )
    .unwrap();
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o755)).unwrap();
    path
}

/// C-069 / D-V12: the marker is **discriminating by construction**.
///
/// Three arms in one test so it cannot pass vacuously: the real
/// `unix_launcher_body` output is not refused, the real `unix_shim_body`
/// output is not refused, and only a body carrying [`TRAMPOLINE_MARKER`]
/// is. Both non-trampoline bodies come from the **shipped generators**, not
/// from an approximation written here — a predicate keyed on the shared
/// `# Generated by ocx at install time. Do not edit.` header would refuse
/// both and break `ocx launcher exec` and `ocx package exec` outright.
#[cfg(unix)]
#[tokio::test]
async fn the_marker_admits_the_shipped_launcher_and_shim_bodies_and_refuses_only_a_trampoline() {
    use std::collections::BTreeMap;

    use ocx_package::metadata::entrypoint::{Entrypoint, EntrypointName, Entrypoints};

    let tmp = tempfile::tempdir().unwrap();

    // 1. The real package launcher, written by the shipped generator.
    let pkg_root = tmp.path().join("pkg");
    let dest = pkg_root.join("entrypoints");
    let entries = Entrypoints::new(BTreeMap::from([(
        EntrypointName::try_from("cmake").unwrap(),
        Entrypoint::default(),
    )]));
    let shim_bin = ocx_store::file_structure::ShimBinStore::new(tmp.path().join("shim_bin"));
    crate::launcher::generate(&pkg_root, &entries, &dest, &shim_bin)
        .await
        .expect("the shipped generator writes a launcher");
    let launcher = dest.join("cmake");
    assert!(
        std::fs::read_to_string(&launcher)
            .unwrap()
            .contains("# Generated by ocx at install time. Do not edit."),
        "precondition: the shipped launcher really does carry the shared header"
    );
    assert!(
        !is_ocx_trampoline(&launcher),
        "a package launcher is not a trampoline and must keep resolving"
    );

    // 2. The real deferred-tool shim, from the shipped generator.
    let identifier = ocx_oci::PinnedIdentifier::try_from(
        ocx_oci::Identifier::new_registry("cmake", "example.com")
            .clone_with_digest(ocx_oci::Digest::Sha256("a".repeat(64))),
    )
    .expect("a digest-bearing identifier is pinned");
    let shim_path = tmp.path().join("shim-cmake");
    std::fs::write(
        &shim_path,
        crate::launcher::shim_body(&identifier).expect("the shim body renders"),
    )
    .unwrap();
    assert!(
        !is_ocx_trampoline(&shim_path),
        "a lazy shim is not a trampoline and must keep resolving"
    );

    // 3. The trampoline itself.
    let trampoline = write_trampoline(tmp.path(), "trampoline-cmake");
    assert!(
        is_ocx_trampoline(&trampoline),
        "a body carrying TRAMPOLINE_MARKER is the one file that is refused"
    );
}

/// E-21 / T-11: an ordinary **package launcher** whose baked package root
/// spells the marker in its own path text must keep resolving.
///
/// This is the case the bounded-prefix rule alone cannot answer, and it is
/// reachable: WP-6 interpolates an operator-controlled absolute path into
/// every generated body, so a `$OCX_HOME` containing the marker string puts
/// it inside the probed head — line 3, at roughly byte 90, well inside 256.
/// Under a "marker anywhere in the prefix" rule C-069 refuses this file and
/// `ocx launcher exec` breaks for that install: exactly the class D-V12
/// excluded when it rejected keying on the shared header. The line-2 anchor
/// is what closes it.
///
/// The body comes from the **shipped generator**, not an approximation, so
/// the test cannot pass by mis-modelling the layout it is asserting about.
#[cfg(unix)]
#[tokio::test]
async fn a_launcher_whose_baked_path_spells_the_marker_is_not_refused() {
    use std::collections::BTreeMap;

    use ocx_package::metadata::entrypoint::{Entrypoint, EntrypointName, Entrypoints};

    let tmp = tempfile::tempdir().unwrap();
    // A package root whose own directory name is the marker — the shape a
    // hostile-or-just-unlucky `$OCX_HOME` produces.
    let pkg_root = tmp.path().join(TRAMPOLINE_MARKER).join("pkg");
    let dest = pkg_root.join("entrypoints");
    let entries = Entrypoints::new(BTreeMap::from([(
        EntrypointName::try_from("cmake").unwrap(),
        Entrypoint::default(),
    )]));
    let shim_bin = ocx_store::file_structure::ShimBinStore::new(tmp.path().join("shim_bin"));
    crate::launcher::generate(&pkg_root, &entries, &dest, &shim_bin)
        .await
        .expect("the shipped generator writes a launcher");
    let launcher = dest.join("cmake");

    let body = std::fs::read(&launcher).unwrap();
    let head = &body[..TRAMPOLINE_PROBE_BYTES.min(body.len())];
    let needle = TRAMPOLINE_MARKER.as_bytes();
    assert!(
        head.windows(needle.len()).any(|window| window == needle),
        "precondition: the marker must really be inside the probed head, or this \
             fixture proves nothing about the anchor"
    );
    assert_ne!(
        body.split(|byte| *byte == b'\n').nth(1),
        Some(needle),
        "precondition: and it must NOT be on line two — that is the difference \
             the anchor reads"
    );

    assert!(
        !is_ocx_trampoline(&launcher),
        "a package launcher that merely bakes the marker in its path is not a \
             trampoline; refusing it would break `ocx launcher exec` for that install"
    );
}
