// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OCX Authors

//! Exit codes, error categories and details, and the success checks that fail closed.

use super::types::{
    AttestationStatus, CapabilityStatus, ErrorCategory, ErrorDetail, ExitCode, ListingStatus, ScriptStatus, SlotStatus,
    SweptStatus,
};

impl ExitCode {
    /// Whether the process succeeded. Any other code, one the SDK does not know included, is a failure.
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Success)
    }

    /// The category of failure the code stands for.
    pub fn category(&self) -> Option<ErrorCategory> {
        match self {
            Self::Success => Some(ErrorCategory::Internal),
            Self::Failure => Some(ErrorCategory::Internal),
            Self::UsageError => Some(ErrorCategory::UsageError),
            Self::DataError => Some(ErrorCategory::DataError),
            Self::Unavailable => Some(ErrorCategory::Unavailable),
            Self::IoError => Some(ErrorCategory::IoError),
            Self::TempFail => Some(ErrorCategory::TempFail),
            Self::PermissionDenied => Some(ErrorCategory::PermissionDenied),
            Self::ConfigError => Some(ErrorCategory::ConfigError),
            Self::NotFound => Some(ErrorCategory::NotFound),
            Self::AuthError => Some(ErrorCategory::AuthError),
            Self::PolicyBlocked => Some(ErrorCategory::PermissionDenied),
            Self::Unsupported => Some(ErrorCategory::Unsupported),
            _ => None,
        }
    }
}

impl ErrorDetail {
    /// The exit code a failure with this detail ships under.
    pub fn exit_code(&self) -> Option<ExitCode> {
        match self {
            Self::ActivationFailed => Some(ExitCode::Failure),
            Self::AgnosticPlatformLibcClaim => Some(ExitCode::DataError),
            Self::AmbiguousExtraCaCerts => Some(ExitCode::ConfigError),
            Self::AmbiguousHostLeaf => Some(ExitCode::DataError),
            Self::AmbiguousTrustRoot => Some(ExitCode::ConfigError),
            Self::AnnounceFailed => Some(ExitCode::Failure),
            Self::AnyPinNotAdvertisedAsAny => Some(ExitCode::DataError),
            Self::AnyPinProvenanceUnavailable => Some(ExitCode::Failure),
            Self::ArchiveEntryEscape => Some(ExitCode::DataError),
            Self::ArchiveExtractedNoEntries => Some(ExitCode::DataError),
            Self::ArchiveExtractionCapExceeded => Some(ExitCode::DataError),
            Self::ArchiveGnuSparseUnsupported => Some(ExitCode::DataError),
            Self::ArchiveHardLinkEscape => Some(ExitCode::DataError),
            Self::ArchiveInternal => Some(ExitCode::Failure),
            Self::ArchiveIo => Some(ExitCode::IoError),
            Self::ArchiveSymlinkEscape => Some(ExitCode::DataError),
            Self::ArchiveTarInvalid => Some(ExitCode::DataError),
            Self::ArchiveUnsupportedFormat => Some(ExitCode::DataError),
            Self::ArchiveZipInvalid => Some(ExitCode::DataError),
            Self::AttestationBudgetExhausted => Some(ExitCode::DataError),
            Self::AttestationNotFound => Some(ExitCode::NotFound),
            Self::AttestationPayloadTooLarge => Some(ExitCode::DataError),
            Self::AttestationTooLarge => Some(ExitCode::DataError),
            Self::AuthEnvMissing => Some(ExitCode::ConfigError),
            Self::BinScanFailed => Some(ExitCode::Failure),
            Self::BinScanUnsupportedHost => Some(ExitCode::DataError),
            Self::BindingAlreadyExists => Some(ExitCode::UsageError),
            Self::BindingAmbiguous => Some(ExitCode::UsageError),
            Self::BindingNotDeclared => Some(ExitCode::NotFound),
            Self::BindingNotFound => Some(ExitCode::NotFound),
            Self::BindingNotSelected => Some(ExitCode::UsageError),
            Self::BindingValueInvalid => Some(ExitCode::ConfigError),
            Self::BindingValueMissingRegistry => Some(ExitCode::ConfigError),
            Self::BlobNotFound => Some(ExitCode::NotFound),
            Self::BotIdentity => Some(ExitCode::UsageError),
            Self::BuildReceiptNotFound => Some(ExitCode::NotFound),
            Self::BuilderMismatch => Some(ExitCode::DataError),
            Self::BundleParseFailed => Some(ExitCode::DataError),
            Self::CandidateLimitExhausted => Some(ExitCode::DataError),
            Self::CatalogDocumentAbsent => Some(ExitCode::Unavailable),
            Self::CertChainInvalid => Some(ExitCode::DataError),
            Self::CertificateValidityWindow => Some(ExitCode::DataError),
            Self::CiExportWrite => Some(ExitCode::IoError),
            Self::CiFileWrite => Some(ExitCode::IoError),
            Self::CiMissingEnv => Some(ExitCode::ConfigError),
            Self::ClientInternal => Some(ExitCode::Failure),
            Self::ClientIo => Some(ExitCode::IoError),
            Self::ClientSerialization => Some(ExitCode::DataError),
            Self::CommandNotExecutable => Some(ExitCode::DataError),
            Self::CommandNotFound => Some(ExitCode::DataError),
            Self::CommandTrampolineRefused => Some(ExitCode::DataError),
            Self::CommittedTagsDropped => Some(ExitCode::DataError),
            Self::CompressionCreate => Some(ExitCode::IoError),
            Self::CompressionDecodeOnly => Some(ExitCode::DataError),
            Self::CompressionEngineInit => Some(ExitCode::Failure),
            Self::CompressionIo => Some(ExitCode::IoError),
            Self::CompressionOpen => Some(ExitCode::IoError),
            Self::CompressionUnknownFormat => Some(ExitCode::DataError),
            Self::ConfigEditIo => Some(ExitCode::IoError),
            Self::ConfigEditLocked => Some(ExitCode::TempFail),
            Self::ConfigEditMalformed => Some(ExitCode::IoError),
            Self::ConfigEditParse => Some(ExitCode::IoError),
            Self::ConfigEditTooLarge => Some(ExitCode::ConfigError),
            Self::ConfigFileNotFound => Some(ExitCode::NotFound),
            Self::ConfigFileTooLarge => Some(ExitCode::ConfigError),
            Self::ConfigIo => Some(ExitCode::IoError),
            Self::ConfigParse => Some(ExitCode::ConfigError),
            Self::CredentialHelperFailed => Some(ExitCode::AuthError),
            Self::CredentialHelperInvalidJson => Some(ExitCode::DataError),
            Self::CredentialHelperNotOnPath => Some(ExitCode::ConfigError),
            Self::CredentialHelperTimeout => Some(ExitCode::TempFail),
            Self::CredentialHelperUnsafePath => Some(ExitCode::ConfigError),
            Self::CredentialStoreWrite => Some(ExitCode::IoError),
            Self::DeclaredBinaryNotExecutable => Some(ExitCode::DataError),
            Self::DecompressionCapExceeded => Some(ExitCode::DataError),
            Self::DeleteNeedsTag => Some(ExitCode::UsageError),
            Self::DependencyAmbiguousPlatform => Some(ExitCode::DataError),
            Self::DependencyConflict => Some(ExitCode::DataError),
            Self::DependencyDeclarationInvalid => Some(ExitCode::DataError),
            Self::DependencyManifestNotFound => Some(ExitCode::NotFound),
            Self::DependencyNoCompatiblePlatform => Some(ExitCode::DataError),
            Self::DependencyNotFound => Some(ExitCode::NotFound),
            Self::DependencyPinResolutionFailed => Some(ExitCode::Failure),
            Self::DependencyPinVerificationFailed => Some(ExitCode::Failure),
            Self::DependencyPinnedToIndex => Some(ExitCode::DataError),
            Self::DependencyRoutingFailed => Some(ExitCode::Failure),
            Self::DependencySetupFailed => Some(ExitCode::Failure),
            Self::DescDisappeared => Some(ExitCode::DataError),
            Self::DestinationCheckIo => Some(ExitCode::IoError),
            Self::DestinationNotADirectory => Some(ExitCode::UsageError),
            Self::DestinationNotEmpty => Some(ExitCode::UsageError),
            Self::DestinationThroughSymlink => Some(ExitCode::UsageError),
            Self::DigestMismatch => Some(ExitCode::DataError),
            Self::DigestMissing => Some(ExitCode::DataError),
            Self::DirectDigestPinInAnyTarget => Some(ExitCode::DataError),
            Self::DispatchObjectDigestMismatch => Some(ExitCode::DataError),
            Self::DockerCredentialRetrieval => Some(ExitCode::AuthError),
            Self::DuplicateBindingAcrossGroups => Some(ExitCode::UsageError),
            Self::DuplicateOwner => Some(ExitCode::UsageError),
            Self::DuplicatePlatformKey => Some(ExitCode::DataError),
            Self::EmptyGroupFilter => Some(ExitCode::UsageError),
            Self::EmptyPushSet => Some(ExitCode::DataError),
            Self::EndpointUnresolvable => Some(ExitCode::Unavailable),
            Self::EntrypointCollision => Some(ExitCode::DataError),
            Self::EnvrcExists => Some(ExitCode::ConfigError),
            Self::ExtraCaCertsInvalid => Some(ExitCode::DataError),
            Self::ExtraCaCertsNotUtf8 => Some(ExitCode::DataError),
            Self::ExtraCaCertsPemInvalid => Some(ExitCode::ConfigError),
            Self::ExtraCaCertsReadFailed => Some(ExitCode::IoError),
            Self::ExtraCaFileInvalid => Some(ExitCode::DataError),
            Self::ExtraCaFileTooLarge => Some(ExitCode::IoError),
            Self::ExtraCaUnreadable => Some(ExitCode::IoError),
            Self::ExtraCaValueInvalid => Some(ExitCode::ConfigError),
            Self::ExtraCaValueTooLarge => Some(ExitCode::ConfigError),
            Self::FeatureMismatch => Some(ExitCode::DataError),
            Self::FileIo => Some(ExitCode::IoError),
            Self::ForbiddenRegistryTarget => Some(ExitCode::ConfigError),
            Self::ForgeAuthFailed => Some(ExitCode::AuthError),
            Self::ForgeCapabilityUnavailable => Some(ExitCode::Unsupported),
            Self::ForgeClientBuild => Some(ExitCode::Failure),
            Self::ForgeCredentialMissing => Some(ExitCode::AuthError),
            Self::ForgeDecode => Some(ExitCode::Failure),
            Self::ForgeFailed => Some(ExitCode::Failure),
            Self::ForgeKindUnknown => Some(ExitCode::UsageError),
            Self::ForgeMissingField => Some(ExitCode::Failure),
            Self::ForgeNonFastForward => Some(ExitCode::TempFail),
            Self::ForgePublisherNotAllowlisted => Some(ExitCode::PermissionDenied),
            Self::ForgePushAccessDenied => Some(ExitCode::AuthError),
            Self::ForgePushRefused => Some(ExitCode::PermissionDenied),
            Self::ForgeRequestEncode => Some(ExitCode::Failure),
            Self::ForgeRequired => Some(ExitCode::Failure),
            Self::ForgeStaleLease => Some(ExitCode::TempFail),
            Self::ForgeStatus => Some(ExitCode::Failure),
            Self::ForgeTransient => Some(ExitCode::TempFail),
            Self::ForgeTransportFailed => Some(ExitCode::Unavailable),
            Self::ForgeTransportOperationUnsupported => Some(ExitCode::UsageError),
            Self::ForgeTransportTransient => Some(ExitCode::TempFail),
            Self::ForgeTransportUnsupported => Some(ExitCode::UsageError),
            Self::ForgeUnavailable => Some(ExitCode::Unavailable),
            Self::ForkBaseUnreachable => Some(ExitCode::Failure),
            Self::ForkFieldMissing => Some(ExitCode::Failure),
            Self::ForkHostMismatch => Some(ExitCode::UsageError),
            Self::ForkNotReady => Some(ExitCode::Failure),
            Self::ForkOwnerMismatch => Some(ExitCode::Failure),
            Self::ForkParentAbsent => Some(ExitCode::Failure),
            Self::ForkParentMismatch => Some(ExitCode::Failure),
            Self::ForwardedEnvInvalid => Some(ExitCode::DataError),
            Self::FrozenRefused => Some(ExitCode::PolicyBlocked),
            Self::FulcioBadRequest => Some(ExitCode::ConfigError),
            Self::FulcioUnavailable => Some(ExitCode::TempFail),
            Self::GitCommandFailed => Some(ExitCode::Failure),
            Self::GitPushFailed => Some(ExitCode::Failure),
            Self::GitUnavailable => Some(ExitCode::Unavailable),
            Self::GroupHoldsDirectBinding => Some(ExitCode::ConfigError),
            Self::HostResolutionFailed => Some(ExitCode::TempFail),
            Self::IdentityMismatch => Some(ExitCode::PermissionDenied),
            Self::IdentityTokenFilePermissive => Some(ExitCode::PermissionDenied),
            Self::IndexDispatchDigestMismatch => Some(ExitCode::DataError),
            Self::IndexHttpFailed => Some(ExitCode::Unavailable),
            Self::IndexHttpTransient => Some(ExitCode::TempFail),
            Self::IndexManifestNotFound => Some(ExitCode::NotFound),
            Self::IndexNamedByDigest => Some(ExitCode::UsageError),
            Self::IndexPathInvalid => Some(ExitCode::Failure),
            Self::IndexResolutionBlocked => Some(ExitCode::PolicyBlocked),
            Self::IndexRootMissingField => Some(ExitCode::Failure),
            Self::IndexRootNotObject => Some(ExitCode::Failure),
            Self::IndexRootParse => Some(ExitCode::Failure),
            Self::IndexSerialization => Some(ExitCode::DataError),
            Self::IndexSingleflightFailed => Some(ExitCode::Failure),
            Self::IndexSourceFailed => Some(ExitCode::Failure),
            Self::IndexSourceNotPublished => Some(ExitCode::ConfigError),
            Self::IntegrationNamespaceInvalid => Some(ExitCode::DataError),
            Self::IntegrationTooLarge => Some(ExitCode::DataError),
            Self::IntegrationsTooLarge => Some(ExitCode::DataError),
            Self::Internal => Some(ExitCode::Failure),
            Self::InternalPathInvalid => Some(ExitCode::Failure),
            Self::InvalidAuthType => Some(ExitCode::ConfigError),
            Self::InvalidBinaryName => Some(ExitCode::DataError),
            Self::InvalidBindingName => Some(ExitCode::UsageError),
            Self::InvalidBooleanString => Some(ExitCode::DataError),
            Self::InvalidBuildMetadata => Some(ExitCode::DataError),
            Self::InvalidCommandLine => Some(ExitCode::UsageError),
            Self::InvalidDigest => Some(ExitCode::DataError),
            Self::InvalidEncoding => Some(ExitCode::DataError),
            Self::InvalidEndpointUrl => Some(ExitCode::UsageError),
            Self::InvalidEnv => Some(ExitCode::ConfigError),
            Self::InvalidGroupName => Some(ExitCode::UsageError),
            Self::InvalidIdentifier => Some(ExitCode::DataError),
            Self::InvalidImageIndex => Some(ExitCode::DataError),
            Self::InvalidIndexUrl => Some(ExitCode::ConfigError),
            Self::InvalidLayerLayout => Some(ExitCode::DataError),
            Self::InvalidLayerRef => Some(ExitCode::UsageError),
            Self::InvalidListSeparator => Some(ExitCode::DataError),
            Self::InvalidLogoContent => Some(ExitCode::DataError),
            Self::InvalidManagedConfigSource => Some(ExitCode::ConfigError),
            Self::InvalidManifest => Some(ExitCode::DataError),
            Self::InvalidOwnerLogin => Some(ExitCode::UsageError),
            Self::InvalidPlatform => Some(ExitCode::DataError),
            Self::InvalidRepoCoordinate => Some(ExitCode::UsageError),
            Self::InvalidTag => Some(ExitCode::UsageError),
            Self::InvalidToolchainNameCharset => Some(ExitCode::ConfigError),
            Self::InvalidTrustPolicy => Some(ExitCode::ConfigError),
            Self::InvalidVersionSpec => Some(ExitCode::UsageError),
            Self::IssuerMismatch => Some(ExitCode::PermissionDenied),
            Self::JsonSerialization => Some(ExitCode::DataError),
            Self::KeyBackendUnavailable => Some(ExitCode::TempFail),
            Self::KeyMalformed => Some(ExitCode::DataError),
            Self::KeyReferenceInvalid => Some(ExitCode::UsageError),
            Self::KeyUnreadable => Some(ExitCode::IoError),
            Self::LaunchIdentitiesInvalid => Some(ExitCode::ConfigError),
            Self::LaunchSpawnFailed => Some(ExitCode::Failure),
            Self::LauncherPathNotUtf8 => Some(ExitCode::DataError),
            Self::LauncherUnsafeCharacter => Some(ExitCode::DataError),
            Self::LayerLayoutFailed => Some(ExitCode::Failure),
            Self::LayerNotStaged => Some(ExitCode::Failure),
            Self::LayerSizeExceeded => Some(ExitCode::DataError),
            Self::LibcLintRead => Some(ExitCode::IoError),
            Self::LibcLintScanFailed => Some(ExitCode::Failure),
            Self::LibcScanScopeModifier => Some(ExitCode::DataError),
            Self::LibcScanScopeUnresolvable => Some(ExitCode::DataError),
            Self::LinkPathOccupied => Some(ExitCode::DataError),
            Self::ListSeparatorInvalid => Some(ExitCode::DataError),
            Self::LockMissing => Some(ExitCode::ConfigError),
            Self::LockRepositoryNotBare => Some(ExitCode::ConfigError),
            Self::LockStale => Some(ExitCode::DataError),
            Self::LoginRejected => Some(ExitCode::AuthError),
            Self::MalformedCatalogKey => Some(ExitCode::DataError),
            Self::MalformedForkFullName => Some(ExitCode::Failure),
            Self::MalformedIndexDocument => Some(ExitCode::DataError),
            Self::MalformedPhysicalRef => Some(ExitCode::DataError),
            Self::MalformedPhysicalRepository => Some(ExitCode::Failure),
            Self::MalformedRepository => Some(ExitCode::UsageError),
            Self::MalformedRootDocument => Some(ExitCode::DataError),
            Self::ManagedConfigContainsManagedSection => Some(ExitCode::ConfigError),
            Self::ManagedConfigEntryTooLarge => Some(ExitCode::DataError),
            Self::ManagedConfigInputNotFound => Some(ExitCode::NotFound),
            Self::ManagedConfigInvalid => Some(ExitCode::ConfigError),
            Self::ManagedConfigInvalidArchive => Some(ExitCode::DataError),
            Self::ManagedConfigInvalidToml => Some(ExitCode::DataError),
            Self::ManagedConfigKeyByPath => Some(ExitCode::ConfigError),
            Self::ManagedConfigLayerDigestMismatch => Some(ExitCode::DataError),
            Self::ManagedConfigLayerSizeExceeded => Some(ExitCode::DataError),
            Self::ManagedConfigMissingConfigToml => Some(ExitCode::DataError),
            Self::ManagedConfigNoAnyPlatform => Some(ExitCode::DataError),
            Self::ManagedConfigNoGzipLayer => Some(ExitCode::DataError),
            Self::ManagedConfigPayloadInvalidToml => Some(ExitCode::ConfigError),
            Self::ManagedConfigPayloadReadFailed => Some(ExitCode::IoError),
            Self::ManagedConfigPayloadTooLarge => Some(ExitCode::ConfigError),
            Self::ManagedConfigSnapshotWrite => Some(ExitCode::IoError),
            Self::ManagedConfigSourceNotFound => Some(ExitCode::NotFound),
            Self::ManagedConfigStageFailed => Some(ExitCode::IoError),
            Self::ManagedConfigUnexpectedManifest => Some(ExitCode::DataError),
            Self::ManagedConfigUpdateFailed => Some(ExitCode::Failure),
            Self::ManifestNotFound => Some(ExitCode::NotFound),
            Self::MergeRequestUnconfirmed => Some(ExitCode::TempFail),
            Self::MetadataAmbiguous => Some(ExitCode::UsageError),
            Self::MetadataBlobTooLarge => Some(ExitCode::DataError),
            Self::MetadataInvalidLayerPath => Some(ExitCode::UsageError),
            Self::MetadataRequired => Some(ExitCode::UsageError),
            Self::MirrorConfigInvalid => Some(ExitCode::ConfigError),
            Self::MissingBaseRef => Some(ExitCode::Failure),
            Self::MissingDigest => Some(ExitCode::DataError),
            Self::MissingHeadRoot => Some(ExitCode::Failure),
            Self::MissingListSeparator => Some(ExitCode::DataError),
            Self::MultipleAttestations => Some(ExitCode::DataError),
            Self::MultipleSignatures => Some(ExitCode::DataError),
            Self::NestedImageIndex => Some(ExitCode::DataError),
            Self::NestedNamespaceUnsupported => Some(ExitCode::UsageError),
            Self::NoActingIdentity => Some(ExitCode::UsageError),
            Self::NoCredentialStore => Some(ExitCode::ConfigError),
            Self::NoCuratedTags => Some(ExitCode::UsageError),
            Self::NoHostLeaf => Some(ExitCode::ConfigError),
            Self::NoIdentityProvided => Some(ExitCode::UsageError),
            Self::NoIndexableTag => Some(ExitCode::NotFound),
            Self::NoMatchingPlatform => Some(ExitCode::UsageError),
            Self::NoProject => Some(ExitCode::UsageError),
            Self::NoProjectIn => Some(ExitCode::UsageError),
            Self::NoSignaturesFound => Some(ExitCode::NotFound),
            Self::NoUsableBundle => Some(ExitCode::NotFound),
            Self::NonUtf8WireName => Some(ExitCode::DataError),
            Self::NoncanonicalPlatformKey => Some(ExitCode::DataError),
            Self::NotAManifest => Some(ExitCode::DataError),
            Self::NotInIndex => Some(ExitCode::NotFound),
            Self::ObserveRaced => Some(ExitCode::TempFail),
            Self::OcxHomeNeedsNoConsent => Some(ExitCode::UsageError),
            Self::OfflineAttestRefused => Some(ExitCode::PolicyBlocked),
            Self::OfflineManifestMissing => Some(ExitCode::PolicyBlocked),
            Self::OfflineMode => Some(ExitCode::PolicyBlocked),
            Self::OfflineSignRefused => Some(ExitCode::PolicyBlocked),
            Self::OidcPreCheckFailed => Some(ExitCode::PermissionDenied),
            Self::OidcTokenRejected => Some(ExitCode::AuthError),
            Self::OidcTokenUnavailable => Some(ExitCode::TempFail),
            Self::OutputWrite => Some(ExitCode::IoError),
            Self::OwnerIdMismatch => Some(ExitCode::UsageError),
            Self::OwnerUnknown => Some(ExitCode::NotFound),
            Self::PackageAuthoringInvalid => Some(ExitCode::DataError),
            Self::PackageFileIo => Some(ExitCode::IoError),
            Self::PackageInternal => Some(ExitCode::Failure),
            Self::PackageKeyInvalid => Some(ExitCode::ConfigError),
            Self::PackageKeyMissingRegistry => Some(ExitCode::ConfigError),
            Self::PackageManagerInternalFile => Some(ExitCode::IoError),
            Self::PackageManagerSerialization => Some(ExitCode::DataError),
            Self::PackageNotFound => Some(ExitCode::NotFound),
            Self::PackageSerialization => Some(ExitCode::DataError),
            Self::PackageTaskFailed => Some(ExitCode::Failure),
            Self::PatchBlobWriteFailed => Some(ExitCode::IoError),
            Self::PatchConfigInvalid => Some(ExitCode::ConfigError),
            Self::PatchDescriptorInvalidJson => Some(ExitCode::DataError),
            Self::PatchDescriptorTooLarge => Some(ExitCode::DataError),
            Self::PatchDescriptorUnsupportedVersion => Some(ExitCode::DataError),
            Self::PatchDescriptorVanished => Some(ExitCode::NotFound),
            Self::PatchDiscoveryFailed => Some(ExitCode::Failure),
            Self::PatchLayerDigestMismatch => Some(ExitCode::DataError),
            Self::PatchLayerSizeExceeded => Some(ExitCode::DataError),
            Self::PatchManifestDigestMismatch => Some(ExitCode::DataError),
            Self::PatchPolicyBlocked => Some(ExitCode::PolicyBlocked),
            Self::PatchProjectConfigUnreadable => Some(ExitCode::ConfigError),
            Self::PatchSnapshotActive => Some(ExitCode::ConfigError),
            Self::PatchSnapshotDescriptorMissing => Some(ExitCode::NotFound),
            Self::PatchSnapshotUnsupportedVersion => Some(ExitCode::DataError),
            Self::PatchUnexpectedArtifactType => Some(ExitCode::DataError),
            Self::PatchUnexpectedLayerMediaType => Some(ExitCode::DataError),
            Self::PatchUnexpectedManifest => Some(ExitCode::DataError),
            Self::PatchWrongLayerCount => Some(ExitCode::DataError),
            Self::PathEscape => Some(ExitCode::DataError),
            Self::PayloadTypeUnsupported => Some(ExitCode::DataError),
            Self::PermissionDenied => Some(ExitCode::PermissionDenied),
            Self::PinDigestMismatch => Some(ExitCode::DataError),
            Self::PinnedIdentifierMissingDigest => Some(ExitCode::DataError),
            Self::PlainHttpIndexNotAllowed => Some(ExitCode::ConfigError),
            Self::PlatformAmbiguous => Some(ExitCode::UsageError),
            Self::PlatformRequired => Some(ExitCode::UsageError),
            Self::PredicateNotJson => Some(ExitCode::DataError),
            Self::PredicateTooLarge => Some(ExitCode::DataError),
            Self::PredicateTypeMismatch => Some(ExitCode::DataError),
            Self::ProjectAlreadyExists => Some(ExitCode::UsageError),
            Self::ProjectEnvInvalidKey => Some(ExitCode::ConfigError),
            Self::ProjectEnvInvalidSeparator => Some(ExitCode::ConfigError),
            Self::ProjectEnvInvalidValue => Some(ExitCode::ConfigError),
            Self::ProjectEnvPathSeparatorInValue => Some(ExitCode::DataError),
            Self::ProjectEnvReservedKey => Some(ExitCode::ConfigError),
            Self::ProjectEnvSeparatorEdgedValue => Some(ExitCode::ConfigError),
            Self::ProjectEnvSeparatorOnNonList => Some(ExitCode::ConfigError),
            Self::ProjectEnvUnknownModifier => Some(ExitCode::ConfigError),
            Self::ProjectEnvUnknownValueField => Some(ExitCode::ConfigError),
            Self::ProjectFileTooLarge => Some(ExitCode::ConfigError),
            Self::ProjectInternalFile => Some(ExitCode::IoError),
            Self::ProjectIo => Some(ExitCode::IoError),
            Self::ProjectLoadFailed => Some(ExitCode::Failure),
            Self::ProjectLocked => Some(ExitCode::TempFail),
            Self::ProjectManifestEditDiverged => Some(ExitCode::Failure),
            Self::ProjectManifestNotEditable => Some(ExitCode::ConfigError),
            Self::ProjectRegistryIo => Some(ExitCode::IoError),
            Self::ProjectResolutionBlocked => Some(ExitCode::PolicyBlocked),
            Self::ProjectTomlInvalid => Some(ExitCode::ConfigError),
            Self::ProjectTomlSerialize => Some(ExitCode::ConfigError),
            Self::ProvenanceVersionUnsupported => Some(ExitCode::UsageError),
            Self::PruneDigestTag => Some(ExitCode::UsageError),
            Self::PruneNoIndex => Some(ExitCode::PolicyBlocked),
            Self::PruneNotAPrerelease => Some(ExitCode::UsageError),
            Self::PrunePackageNotBare => Some(ExitCode::UsageError),
            Self::PruneRefusedDurable => Some(ExitCode::PolicyBlocked),
            Self::PruneRefusedPending => Some(ExitCode::TempFail),
            Self::PruneTagStillPresent => Some(ExitCode::TempFail),
            Self::PullRequestUnmergeable => Some(ExitCode::DataError),
            Self::PushOptionRefused => Some(ExitCode::Failure),
            Self::RecordExemptionRefused => Some(ExitCode::IoError),
            Self::RecordInputsIncomplete => Some(ExitCode::Failure),
            Self::RecordNameNotAFilename => Some(ExitCode::ConfigError),
            Self::RecordSerializeFailed => Some(ExitCode::IoError),
            Self::RecordSinkSymlink => Some(ExitCode::ConfigError),
            Self::RecordTemplateNotUnique => Some(ExitCode::ConfigError),
            Self::RecordTemplateUnknownPlaceholder => Some(ExitCode::ConfigError),
            Self::RecordWriteFailed => Some(ExitCode::IoError),
            Self::RecordsRequiredWithoutSink => Some(ExitCode::ConfigError),
            Self::ReferrersUnsupported => Some(ExitCode::Unsupported),
            Self::RegistryAuthFailed => Some(ExitCode::AuthError),
            Self::RegistryDeleteUnsupported => Some(ExitCode::Unsupported),
            Self::RegistryTransient => Some(ExitCode::TempFail),
            Self::RegistryUnavailable => Some(ExitCode::Unavailable),
            Self::RegistryUnreachable => Some(ExitCode::Unavailable),
            Self::RekorInclusionProofAbsent => Some(ExitCode::DataError),
            Self::RekorSetAbsentTsaPresent => Some(ExitCode::DataError),
            Self::RekorSetInvalid => Some(ExitCode::DataError),
            Self::RekorSetMalformed => Some(ExitCode::DataError),
            Self::RekorUploadRequiredForKeyless => Some(ExitCode::UsageError),
            Self::RenderedConfigTooLarge => Some(ExitCode::ConfigError),
            Self::RepositoryEscapesIndexHome => Some(ExitCode::DataError),
            Self::RepositoryMismatch => Some(ExitCode::DataError),
            Self::RepositoryNotFound => Some(ExitCode::NotFound),
            Self::RequiredPathMissing => Some(ExitCode::NotFound),
            Self::ReservedEnvKey => Some(ExitCode::DataError),
            Self::ReservedGroupName => Some(ExitCode::ConfigError),
            Self::ResolveTimeout => Some(ExitCode::TempFail),
            Self::RetiredEnv => Some(ExitCode::ConfigError),
            Self::RootNameMismatch => Some(ExitCode::DataError),
            Self::RootRepositoryMismatch => Some(ExitCode::DataError),
            Self::SameFilesystemCheckFailed => Some(ExitCode::IoError),
            Self::SbomMediaTypeUnsupported => Some(ExitCode::DataError),
            Self::SelectionAmbiguous => Some(ExitCode::DataError),
            Self::SelfForkRefused => Some(ExitCode::UsageError),
            Self::SeparatorEdgedListValue => Some(ExitCode::DataError),
            Self::SessionPathNotAbsolute => Some(ExitCode::ConfigError),
            Self::SessionPathNotUtf8 => Some(ExitCode::ConfigError),
            Self::SessionPathUnencodable => Some(ExitCode::ConfigError),
            Self::SetupBootstrapFailed => Some(ExitCode::Failure),
            Self::SetupIo => Some(ExitCode::IoError),
            Self::SetupProfileSubprocess => Some(ExitCode::Unavailable),
            Self::ShellSectionInProject => Some(ExitCode::ConfigError),
            Self::ShimClaimUnfulfilled => Some(ExitCode::DataError),
            Self::ShimNameInvalid => Some(ExitCode::DataError),
            Self::ShimNameNotClaimed => Some(ExitCode::DataError),
            Self::ShimNamesNotEnumerable => Some(ExitCode::DataError),
            Self::ShortBlobRead => Some(ExitCode::TempFail),
            Self::SidecarRequiresSignature => Some(ExitCode::UsageError),
            Self::SignatureInvalid => Some(ExitCode::DataError),
            Self::SimpleSigningClaimUnsupported => Some(ExitCode::DataError),
            Self::SingleflightAbandoned => Some(ExitCode::Failure),
            Self::SingleflightCapacityExceeded => Some(ExitCode::TempFail),
            Self::SingleflightFailed => Some(ExitCode::Failure),
            Self::SingleflightTimeout => Some(ExitCode::TempFail),
            Self::SsrfForbiddenTarget => Some(ExitCode::ConfigError),
            Self::StatementSubjectAbsent => Some(ExitCode::DataError),
            Self::StatementSubjectMismatch => Some(ExitCode::DataError),
            Self::StatementSubjectWeakAlgorithm => Some(ExitCode::DataError),
            Self::StatementTypeUnsupported => Some(ExitCode::DataError),
            Self::SubjectDigestMismatch => Some(ExitCode::DataError),
            Self::SubjectDigestUnsupported => Some(ExitCode::DataError),
            Self::SymlinkNotFound => Some(ExitCode::NotFound),
            Self::SymlinkRequiresTag => Some(ExitCode::DataError),
            Self::SymlinkWalkIo => Some(ExitCode::IoError),
            Self::SystemConfigInvalid => Some(ExitCode::ConfigError),
            Self::TagNotAnImageIndex => Some(ExitCode::DataError),
            Self::TagNotFound => Some(ExitCode::NotFound),
            Self::TargetNotAnIndex => Some(ExitCode::NotFound),
            Self::TargetNotFound => Some(ExitCode::NotFound),
            Self::TaskPanicked => Some(ExitCode::Failure),
            Self::TemplateAmbiguousDependencyRef => Some(ExitCode::DataError),
            Self::TemplateAmbiguousSelfEnvRef => Some(ExitCode::DataError),
            Self::TemplateDependencyNotInstalled => Some(ExitCode::NotFound),
            Self::TemplateDisallowedToken => Some(ExitCode::DataError),
            Self::TemplateModifierNotApplicable => Some(ExitCode::DataError),
            Self::TemplateUndefinedSelfEnvRef => Some(ExitCode::DataError),
            Self::TemplateUnknownDependencyRef => Some(ExitCode::DataError),
            Self::TemplateUnknownField => Some(ExitCode::DataError),
            Self::TemplateUnknownModifier => Some(ExitCode::DataError),
            Self::TemplateUnknownToken => Some(ExitCode::DataError),
            Self::TemplateValueTooLarge => Some(ExitCode::DataError),
            Self::TerminalOutputRefused => Some(ExitCode::UsageError),
            Self::TlogBindingMismatch => Some(ExitCode::DataError),
            Self::TooManyAttestations => Some(ExitCode::DataError),
            Self::ToolchainDirGroupOrWorldWritable => Some(ExitCode::ConfigError),
            Self::ToolchainDirInaccessible => Some(ExitCode::ConfigError),
            Self::ToolchainDirInsideGlobalHome => Some(ExitCode::ConfigError),
            Self::ToolchainDirIsContainmentAnchor => Some(ExitCode::ConfigError),
            Self::ToolchainDirNoContainmentAnchor => Some(ExitCode::ConfigError),
            Self::ToolchainDirNotADirectory => Some(ExitCode::ConfigError),
            Self::ToolchainDirNotOwnerOwned => Some(ExitCode::ConfigError),
            Self::ToolchainDirOutsideHome => Some(ExitCode::ConfigError),
            Self::ToolchainDirParentComponent => Some(ExitCode::ConfigError),
            Self::ToolchainDirRelative => Some(ExitCode::ConfigError),
            Self::ToolchainDirSystemPrefix => Some(ExitCode::ConfigError),
            Self::ToolchainDirUnexpandable => Some(ExitCode::ConfigError),
            Self::ToolchainHomeNotAbsolute => Some(ExitCode::DataError),
            Self::ToolchainNameControlCharacter => Some(ExitCode::ConfigError),
            Self::ToolchainNameEmpty => Some(ExitCode::ConfigError),
            Self::ToolchainNamePathPrefix => Some(ExitCode::ConfigError),
            Self::ToolchainNameRelative => Some(ExitCode::ConfigError),
            Self::ToolchainNameSeparator => Some(ExitCode::ConfigError),
            Self::ToolchainNameTrailingDotOrSpace => Some(ExitCode::ConfigError),
            Self::TransparencyBodyMismatch => Some(ExitCode::DataError),
            Self::TransparencyLogKeyUnavailable => Some(ExitCode::Unavailable),
            Self::TransparencyLogResponseInvalid => Some(ExitCode::DataError),
            Self::TransparencyLogUnavailable => Some(ExitCode::TempFail),
            Self::TransparencyLogUnreachable => Some(ExitCode::Unavailable),
            Self::TraversalLimitExceeded => Some(ExitCode::DataError),
            Self::TrustPolicyInvalid => Some(ExitCode::ConfigError),
            Self::TrustRootLoad => Some(ExitCode::ConfigError),
            Self::TrustRootUnavailable => Some(ExitCode::ConfigError),
            Self::TrustRootUnreadable => Some(ExitCode::IoError),
            Self::TrustedRootInvalid => Some(ExitCode::ConfigError),
            Self::TrustedRootReadFailed => Some(ExitCode::IoError),
            Self::UnclaimedPackage => Some(ExitCode::NotFound),
            Self::UndeclaredBinary => Some(ExitCode::DataError),
            Self::UndeclaredLibc => Some(ExitCode::DataError),
            Self::UnexpectedArtifactType => Some(ExitCode::DataError),
            Self::UnexpectedLayerMediaType => Some(ExitCode::DataError),
            Self::UnexpectedManifestType => Some(ExitCode::DataError),
            Self::UnfollowedRedirect => Some(ExitCode::DataError),
            Self::UnknownCompareStatus => Some(ExitCode::Failure),
            Self::UnknownEnvModifier => Some(ExitCode::DataError),
            Self::UnknownGroup => Some(ExitCode::UsageError),
            Self::UnknownGroupSection => Some(ExitCode::ConfigError),
            Self::UnparseableElf => Some(ExitCode::DataError),
            Self::UnrecognizedInterpreter => Some(ExitCode::DataError),
            Self::UnresolvedTag => Some(ExitCode::NotFound),
            Self::UnsafeDestination => Some(ExitCode::DataError),
            Self::UnsignedRejectedByPolicy => Some(ExitCode::PermissionDenied),
            Self::UnsignedTypeUnsupported => Some(ExitCode::UsageError),
            Self::UnsupportedDeclarationHashVersion => Some(ExitCode::ConfigError),
            Self::UnsupportedIndexFormat => Some(ExitCode::DataError),
            Self::UnsupportedKeyBackend => Some(ExitCode::Unsupported),
            Self::UnsupportedLockVersion => Some(ExitCode::ConfigError),
            Self::UnsupportedLogoFormat => Some(ExitCode::DataError),
            Self::UnsupportedMediaType => Some(ExitCode::DataError),
            Self::UnsupportedTlogEntryKind => Some(ExitCode::DataError),
            Self::UnyankTagNotCurated => Some(ExitCode::Failure),
            Self::UpdateSectionInProject => Some(ExitCode::ConfigError),
            Self::Usage => Some(ExitCode::UsageError),
            Self::UsersApiUnavailable => Some(ExitCode::UsageError),
            Self::VersionInvalid => Some(ExitCode::DataError),
            Self::WalkedDigestMismatch => Some(ExitCode::DataError),
            Self::WrongLayerCount => Some(ExitCode::DataError),
            Self::YankTagNotCurated => Some(ExitCode::Failure),
            Self::YankUnyankOverlap => Some(ExitCode::Failure),
            Self::YankedRefused => Some(ExitCode::DataError),
            _ => None,
        }
    }
}

impl AttestationStatus {
    /// Whether the status is one the SDK vouches for as success. Any other, one it does not know included, is not.
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Succeeded)
    }
}

impl CapabilityStatus {
    /// Whether the status is one the SDK vouches for as success. Any other, one it does not know included, is not.
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Passed)
    }
}

impl ListingStatus {
    /// Whether the status is one the SDK vouches for as success. Any other, one it does not know included, is not.
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Success)
    }
}

impl ScriptStatus {
    /// Whether the status is one the SDK vouches for as success. Any other, one it does not know included, is not.
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Passed)
    }
}

impl SlotStatus {
    /// Whether the status is one the SDK vouches for as success. Any other, one it does not know included, is not.
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Ok)
    }
}

impl SweptStatus {
    /// Whether the status is one the SDK vouches for as success. Any other, one it does not know included, is not.
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Completed)
    }
}
