// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The OCX Authors

//! A client for the `ocx` machine interface: one function per command, its reports decoded into types, and the
//! exit codes and error details as `ocx` registers them. Generated by `ocx-sdkgen`; do not edit.

pub mod commands;
pub mod contract;
pub mod env;
mod exit;
pub mod runtime;
pub mod spawn;
pub mod types;
pub mod wire;

pub use commands::*;
pub use runtime::{CancelToken, Error, Handshake, Limits, Ocx, Outcome, Raw};
pub use wire::{Secret, Unknowns};
