#!/usr/bin/env bash
# Generated by ocx-mirror v{OCX_MIRROR_VERSION} (rev {OCX_MIRROR_REV})
# DO NOT EDIT — re-run `ocx-mirror pipeline generate ci` to update.
# Source: mirror.yml
#
# Install branch protection rules on the `main` branch of this repository.
# Requires: gh CLI authenticated with admin access to the repo.
#
# Usage:
#   bash scripts/install-branch-protection.sh
#
set -euo pipefail
IFS=$'\n\t'

REPO="${GITHUB_REPOSITORY:-$(gh repo view --json nameWithOwner -q .nameWithOwner)}"

echo "Installing branch protection on ${REPO}..."

REQUIRED_CHECKS='{REQUIRED_CHECKS_JSON}'

gh api \
    --method PUT \
    "repos/${REPO}/branches/main/protection" \
    --input - <<EOF
{
  "required_status_checks": {
    "strict": false,
    "checks": ${REQUIRED_CHECKS}
  },
  "enforce_admins": false,
  "required_pull_request_reviews": null,
  "restrictions": null
}
EOF

echo "Branch protection installed successfully."
